export type Language = "English" | "Telugu" | "Hindi" | "Tamil" | "Kannada" | "Malayalam";

export const LOCALIZATION_DICTIONARY: Record<Language, Record<string, string>> = {
  English: {
    // Nav & General
    buyerDashboard: "Buyer Dashboard",
    sellerDashboard: "Seller Dashboard",
    userDashboard: "User Dashboard",
    home: "Home",
    profile: "Profile",
    notifications: "Notifications",
    buyerAccount: "Buyer Account",
    langChangedToast: "Language changed to English.",
    allRead: "Mark all read",
    notifCenter: "Notifications Center",
    logout: "Log Out",

    // Home Page
    heroHeading: "Supply Market",
    heroSubtitle: "AI Supplier Match & Call Connect Platform",
    heroDesc: "Supply Market helps buyers quickly find trusted suppliers using Artificial Intelligence. The AI understands your requirement, finds the best supplier, and helps you connect faster.",
    goToBuyer: "Go to Buyer Dashboard",
    goToSeller: "Go to Seller Dashboard",
    howItWorks: "How Supply Market Works",
    howDesc: "Four simple phases translating requirements to secure direct client calls.",
    whyChoose: "Why Choose Supply Market",
    whyDesc: "A premium, simple trade platform engineered to build trust across businesses.",
    step1Title: "Describe requirement",
    step1Desc: "Describe your quantity, quality and location in plain text or voice instructions.",
    step2Title: "AI finds best supplier",
    step2Desc: "Our matching engine searches catalog nodes and grades best fit suppliers.",
    step3Title: "Review supplier details",
    step3Desc: "Compare Indian Rupee pricing, stock buffers, location coordinates and ratings.",
    step4Title: "Connect directly",
    step4Desc: "Click to bridge secure telephone dialer connections to initiate sales reps dialogue.",
    feat1Title: "Fast Supplier Discovery",
    feat1Desc: "Discover matching supplier connections instantly. Save hours of manual market calls.",
    feat2Title: "Trusted Businesses",
    feat2Desc: "Connect only with verified companies having high trust scores and performance credentials.",
    feat3Title: "AI Voice Assistant",
    feat3Desc: "Conversational voice assistant handles matching playback readouts natively.",
    feat4Title: "Multiple Languages",
    feat4Desc: "Speak and receive instructions in 6 Indian languages: Telugu, Hindi, Tamil, Kannada, Malayalam, and English.",
    feat5Title: "Smart Recommendations",
    feat5Desc: "AI lists clear rationale justifications detailing why each option represents your best fit.",
    feat6Title: "Professional Connections",
    feat6Desc: "Save contacts and follow company directories to build recurring wholesale trade trust.",

    // Buyer Dashboard
    findRightSupplier: "Find the Right Supplier",
    tellUsNeed: "Tell us what you need. Our AI will help you find the best supplier.",
    searchPlaceholder: 'Example: "I need 100kg premium turmeric for my herbal products business."',
    speakBtn: "Speak",
    findSuppliersBtn: "Find Suppliers",
    clearBtn: "Clear",
    listeningLabel: "Listening. Speak requirement...",
    matchingSuppliers: "Matching Suppliers...",
    popularSearches: "Popular Searches:",
    processingHeuristics: "Processing Match Heuristics",
    processingDesc: "Evaluating inventory databases and freight corridors.",
    aiRecomHeading: "AI Recommendation Selection",
    bestMatch: "Best Match",
    ratingLabel: "Rating",
    locationLabel: "Location",
    availToday: "Available Today",
    matchScore: "Match Score",
    reasonForRecom: "Reason for recommendation:",
    productOfferPrice: "Product Offer Price",
    connectBtn: "Connect",
    viewDetailsBtn: "View Details",
    saveBtn: "Save",
    savedBtn: "Saved",
    aiSummaryHeading: "AI Sourcing Summary",
    reqLabel: "Your Requirement",
    selSupplierLabel: "Selected Supplier",
    priceLabel: "Price",
    qtyLabel: "Quantity",
    reasonSelLabel: "Reason for Selection",
    nextStepLabel: "Next Step Recommendation",
    otherOptions: "Other Sourced Options",
    browseSuppliersManually: "Browse Suppliers Manually",
    browseDesc: "Search and filter through the complete verified registry database.",
    productSearchLabel: "Product search",
    locationCityLabel: "Location City",
    productCatLabel: "Product Category",
    allCategories: "All Categories",
    minPriceLabel: "Min Price (₹)",
    maxPriceLabel: "Max Price (₹)",
    minRatingLabel: "Min Rating",
    allRatings: "All Ratings",
    availTodayFilter: "Available Today",
    viewBtn: "View",
    followBtn: "Follow",
    followingBtn: "Following",
    noSellersFound: "No matching suppliers found in manual directory search.",

    // Center Voice assistant
    aiSpeaking: "AI Speaking",
    connectSupplier: "Connect Supplier",
    askAi: "Ask AI",
    findMore: "Find More",

    // Stepper Steps
    step1: "Understanding your requirement",
    step2: "Searching suppliers",
    step3: "Comparing prices",
    step4: "Checking stock",
    step5: "Choosing the best supplier",
    step6: "Preparing response",

    // Hotline Handshake Overlay
    connecting: "Connecting...",
    connectingDesc: "Bridging secure call routing lines and syncing profile identity.",
    connSuccessful: "Connection Successful",
    yourIdentity: "Your Identity",
    supplierSourced: "Supplier Sourced",
    connConnected: "Connected",
    connSuccessText: "Buyer and Supplier are now connected. You can continue your discussion directly.",
    callSalesBtn: "Call Sales Rep",
    doneBtn: "Done",

    // Seller Dashboard
    activeListings: "Active catalog listings",
    activeOrders: "Active orders",
    connectedBuyers: "Connected buyers",
    revenueLabel: "Revenue",
    salesValue: "Sales value recorded",
    aiSourcingSug: "AI Sourcing Suggestions",
    inventorySourcingCat: "Inventory Sourcing Catalog",
    inventorySourcingDesc: "Manage details of items matched against active buyer requirements.",
    addProduct: "Add Product",
    editProduct: "Edit Product",
    deleteProduct: "Delete Product",
    recentConnectedBuyers: "Recent Connected Buyers",
    recentConnectedDesc: "Contact coordinates established via Secure AI Voice bridges.",
    viewBuyer: "View Buyer",
    contactBuyer: "Contact Buyer",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    availableTodayModal: "Available Today (Immediate dispatch active)",
    modalAvailable: "Available Today",

    // Inventory Form Fields
    prodNameField: "Product Name",
    catField: "Category",
    priceField: "Price",
    qtyField: "Quantity",
    qualityField: "Quality",
    locField: "Location City",
    busNameField: "Business Name",
    phoneField: "Phone Number",
    availabilityField: "Available",
    actionsField: "Actions",

    // User Dashboard
    userConsole: "User Console",
    userConsoleDesc: "Manage your business connections, activity history, and language profiles.",
    profileIdentity: "Profile Identity",
    hotlineConnections: "Hotline Connections",
    recentActivity: "Recent Activity",
    consoleSettings: "Console Settings",
    headquarters: "Headquarters",
    activeCatalogReg: "Active Catalog Registry",
    bothBadge: "Both (Buyer & Seller)",
    procurementManager: "Procurement & Wholesales Division Manager",
    corporateEmail: "Corporate Email",
    mobilePhone: "Mobile Phone",
    connHotlineTitle: "Business Connection Hotline",
    connHotlineDesc: "Direct link to trusted verified suppliers. You can bypass AI search nodes for saved contacts.",
    removeConn: "Remove",
    sendMessage: "Send Message",
    buyerActivity: "Buyer Activity",
    sellerActivity: "Seller Activity",
    recentSearches: "Recent Searches",
    recentConversationalLogs: "Recent Conversational Audio Logs",
    savedSourcedSuppliers: "Saved Sourced Suppliers",
    hotlinePurchaseHistory: "Hotline Purchase History",
    connectedBuyerActions: "Connected Buyer Actions",
    supplierCatalogChanges: "Supplier Catalog Changes",
    catalogOrders: "Catalog Orders",
    hotRestockSug: "Hot Restock Suggestion",
    systemPref: "System Preferences",
    systemPrefDesc: "Control speech syntheses, input settings, theme preferences, and notification triggers.",
    speechLanguageInterface: "Speech Language Interface",
    themeMode: "Theme Mode",
    toggleModeTheme: "Toggle Mode Theme",
    voiceOutputEngine: "Voice output engine",
    speechMicInput: "Speech microphone input",
    notificationsCenter: "Notifications Center",
    notifConnAlerts: "Sourced connection changes alerts",
    notifStockAlerts: "Stock inventory updates alerts",

    // Seller Advisor Chatbot
    salesAiAssistant: "Sales AI Assistant",
    aiBusinessAdvisor: "AI Business Advisor",
    askSourcingAdvisor: "Ask Sourcing Advisor:",
    typeCustomQuestion: "Type custom question...",
    analyzingSales: "Analyzing your sales...",
    salesAiWelcome: "Hello! I am your Sales AI Assistant. I can help analyze your catalog, predict demand, recommend pricing, or draft business summaries. Select one of the queries below to start:",

    // Chatbot suggestion chips
    chipSoldToday: "How many products sold today?",
    chipSellsMost: "Which product sells the most?",
    chipRestock: "Which product should I restock?",
    chipDecreasing: "Why are sales decreasing?",
    chipPricing: "Suggest better pricing.",
    chipTrends: "Show customer buying trends.",
    chipInventory: "Recommend inventory improvements.",
    chipWeekly: "Generate weekly summary.",
    chipMonthly: "Generate monthly report.",
    chipDemand: "Predict demand.",
    chipBestSelling: "Suggest best selling products.",

    // Chatbot answers
    replySoldToday: "Based on today's logs, you successfully closed completed connections, yielding approximately ₹18,000 in verified volume orders. Active buyers include Verma Food Industries (150 kg Turmeric).",
    replySellsMost: "Your best-performing catalog category is Turmeric. In particular, Premium Turmeric Powder maintains the highest buyer sourcing match velocity, registering 720 matches this month.",
    replyRestock: "Wholesale query alerts suggest that Premium Turmeric Powder is in high demand. Sourcing queries rose 22% this week. We recommend adding 2,000 kg of stock to maintain healthy buffers.",
    replyDecreasing: "Sourcing match velocities for steel and construction cement slowed by 4% across Warangal and Chennai zones due to local seasonal monsoons. However, agricultural food items (Turmeric and Rice) remain highly active.",
    replyPricing: "Due to a 22% increase in regional curcuma sourcing queries, we suggest adjusting Premium Turmeric Powder pricing from ₹120 to ₹125 per kg. This will optimize margins by approximately ₹1,500/week without impacting match scores.",
    replyTrends: "Active buyer logs indicate that wholesalers prefer procuring initial trial sizes (e.g. 50 kg to 200 kg) to inspect quality grades before finalizing multi-ton supply contracts.",
    replyInventory: "Inventory Recommendation:\n1. Upgrade Teakwood seasoning times to target Grade-A verification tags.\n2. Maintain packaging shipping carton stock counts above 5,000 boxes to prevent connection delays.",
    replyWeekly: "Weekly Performance Summary (05 July 2026):\n• Sourced listings: 2 active items\n• Sourced connections: 128 buyers\n• Revenue recorded: ₹1.85 Lakhs\n• Order conversions: +12% growth\n• Trust rating: 4.8★",
    replyMonthly: "Monthly Sourcing Report:\n• Sourcing Search Hits: 1,420 queries\n• Successful Handshakes: 128 connections\n• top match categories: Turmeric, Sona Masoori Rice\n• Sourcing Growth Index: +14.5% MoM",
    replyDemand: "Demand Projection (Next 30 Days):\n• Turmeric Sourcing: High (+18% projected)\n• Rice Sourcing: Stable (+6% projected)\n• Cement/Steel: Moderate growth (+4% in Hyderabad)",
    replyBestSelling: "Highly matched trade products across South India include organic Erode Turmeric Powder, aged Nellore Sona Masoori Rice, and seismic-resistant Structural Fe 550D TMT Rebars.",
    replyGeneric: "Hello! I've analyzed your question. Based on your catalog list of products, maintaining immediate dispatch availability is key to capturing buyer requests. Let me know if you need specific pricing details!",
    aiBusinessInsights: "AI Business Insights",
    highDemandTitle: "🔥 High Buyer Demand",
    highDemandDesc: "{Product} has received many buyer searches this week. Consider increasing available stock.",
    lowStockTitle: "📦 Low Stock Alert",
    lowStockDesc: "{Product} inventory is running low. Restock soon to continue receiving buyer matches.",
    pricingTitle: "💰 Pricing Recommendation",
    pricingDesc: "Your {Product} price is slightly higher than similar suppliers. Reducing the price by ₹5 per {Unit} could improve buyer interest.",
    bestSellingTitle: "⭐ Best Selling Product",
    bestSellingDesc: "{Product} generated the highest revenue this month. Consider promoting this product.",
    demandForecastTitle: "📈 Demand Forecast",
    demandForecastDesc: "Buyer interest for {Product} is expected to increase next week based on recent searches.",
    regionalTrendTitle: "📍 Regional Trend",
    regionalTrendDesc: "Construction materials are currently the fastest growing category in Hyderabad."
  },
  Telugu: {
    buyerDashboard: "బయ్యర్ డాష్‌బోర్డ్",
    sellerDashboard: "సెల్లర్ డాష్‌బోర్డ్",
    userDashboard: "యూజర్ డాష్‌బోర్డ్",
    home: "ホమ్",
    profile: "ప్రొఫైల్",
    notifications: "నోటిఫికేషన్లు",
    buyerAccount: "కొనుగోలుదారు ఖాతా",
    langChangedToast: "భాష తెలుగుకు మార్చబడింది.",
    allRead: "అన్నీ చదివినట్లుగా గుర్తించు",
    notifCenter: "నోటిఫിക്കేషన్ సెంటర్",
    logout: "లాగ్ అవుట్",

    heroHeading: "సప్లై మార్కెట్",
    heroSubtitle: "AI సప్లయర్ మ్యాచ్ & కాల్ కనెక్ట్ ప్లాట్‌ఫారమ్",
    heroDesc: "సప్లై మార్కెట్ ఆర్టిఫిషియల్ ఇంటెలిజెన్స్ ఉపయోగించి కొనుగోలుదారులు విశ్వసనీయ సరఫరాదారులను త్వరగా కనుగొనడంలో సహాయపడుతుంది. AI మీ అవసరాన్ని అర్థం చేసుకుంటుంది, ఉత్తమ సరఫరాదారుని కనుగొంటుంది మరియు మిమ్మల్ని వేగంగా కనెక్ట్ చేయడానికి సహాయపడుతుంది.",
    goToBuyer: "బయ్యర్ డాష్‌బోర్డ్‌కు వెళ్ళండి",
    goToSeller: "సెల్లర్ డాష్‌బోర్డ్‌కు వెళ్ళండి",
    howItWorks: "సప్లై మార్కెట్ ఎలా పనిచేస్తుంది",
    howDesc: "మీ అవసరాలను సురక్షితమైన డైరెక్ట్ కాల్‌లుగా మార్చే నాలుగు సాధారణ దశలు.",
    whyChoose: "సప్లై మార్కెట్‌ను ఎందుకు ఎంచుకోవాలి",
    whyDesc: "వ్యాపారాల మధ్య నమ్మకాన్ని పెంపొందించడానికి రూపొందించబడిన ఒక ప్రీమియం, సాధారణ వాణిజ్య వేదిక.",
    step1Title: "అవసరాన్ని వివరించండి",
    step1Desc: "మీ పరిమాణాన్ని, నాణ్యతను మరియు ప్రాంతాన్ని వచనం లేదా వాయిస్ ద్వారా వివరించండి.",
    step2Title: "AI ఉత్తమ సప్లయర్‌ను కనుగొంటుంది",
    step2Desc: "మా మ్యాచింగ్ ఇంజిన్ కేటలాగ్ వివరాలను శోధించి, అత్యంత సరిపోయే సరఫరాదారులను గ్రేడ్ చేస్తుంది.",
    step3Title: "సరఫరాదారు వివరాలను సమీక్షించండి",
    step3Desc: "రూపాయి ధరలు, స్టాక్ పరిమాణాలు, ప్రాంతం మరియు రేటింగ్‌లను సరిపోల్చండి.",
    step4Title: "నేరుగా కనెక్ట్ అవ్వండి",
    step4Desc: "సంప్రదింపులు జరపడానికి సురక్షితమైన టెలిఫోన్ డయలర్ కనెక్షన్లను ఉపయోగించండి.",
    feat1Title: "వేగవంతమైన సప్లయర్ అన్వేషణ",
    feat1Desc: "సరిపోయే సరఫరాదారులను తక్షణమే కనుగొနండి. గంటల కొద్దీ మార్కెట్ కాల్స్ చేసే సమయాన్ని ఆదా చేసుకోండి.",
    feat2Title: "విశ్వసనీయ వ్యాపారాలు",
    feat2Desc: "అధిక నమ్మక స్కోర్లు మరియు మంచి పనితీరు ఆధారాలు ఉన్న ధృవీకరించబడిన సంస్థలతో మాత్రమే కనెక్ట్ అవ్వండి.",
    feat3Title: "AI వాయిస్ అసిస్టెంట్",
    feat3Desc: "సంభాషణ వాయిస్ అసిస్టెంట్ మ్యాచ్ వివరాల ప్లేబ్యాక్‌ను స్థానికంగా నిర్వహిస్తుంది.",
    feat4Title: "బహుళ భాషలు",
    feat4Desc: "తెలుగు, హిందీ, తమిళం, కన్నడ, మలയാళం మరియు ఇంగ్లీష్: 6 భారతీయ భాషలలో మాట్లాడండి మరియు సూచనలను పొందండి.",
    feat5Title: "స్మార్ట్ సిఫార్సులు",
    feat5Desc: "ప్రతి ఎంపిక మీకు ఎందుకు సరిపోతుందో AI స్పష్టమైన కారణాలను వివరిస్తుంది.",
    feat6Title: "వ్యాపార కనెక్షన్లు",
    feat6Desc: "మళ్ళీ సంప్రదించడానికి కాంటాక్ట్‌లను సేవ్ చేయండి మరియు కంపెనీ డైరెక్టరీలను ఫాలో అవ్వండి.",

    findRightSupplier: "సరైన సరఫరాదారుని కనుగొనండి",
    tellUsNeed: "మీకు కావలసినది మాకు చెప్పండి. మా AI మీకు ఉత్తమ సరఫరాదారుని కనుగొనడంలో సహాయపడుతుంది.",
    searchPlaceholder: 'ఉదాహరణ: "నా హెర్బల్ ఉత్పత్తుల వ్యాపారం కోసం నాకు 100 కిలోల ప్రీమియం పసుపు కావాలి."',
    speakBtn: "వాయిస్",
    findSuppliersBtn: "సరఫరాదారులను కనుగొనండి",
    clearBtn: "క్లియర్",
    listeningLabel: "వింటున్నాము. మీ అవసరాన్ని మాట్లాడండి...",
    matchingSuppliers: "సరఫరాదారులను సరిపోల్చుతున్నాము...",
    popularSearches: "జనాదరణ పొందిన శోధనలు:",
    processingHeuristics: "మ్యాచింగ్ పద్ధతులను ప్రాసెస్ చేస్తున్నాము",
    processingDesc: "ఇన్వెంటరీ డేటాబేస్ మరియు డెలివరీ రూట్లను విశ్లేషిస్తున్నాము.",
    aiRecomHeading: "AI సిఫార్సు ఎంపిక",
    bestMatch: "ఉత్తమ ఎంపిక",
    ratingLabel: "రేటింగ్",
    locationLabel: "ప్రాంతం",
    availToday: "ఈరోజు అందుబాటులో ఉంది",
    matchScore: "మ్యాచ్ స్కోర్",
    reasonForRecom: "సిఫార్సు చేయడానికి కారణం:",
    productOfferPrice: "ఉత్పత్తి ధర",
    connectBtn: "కనెక్ట్",
    viewDetailsBtn: "వివరాలు చూడండి",
    saveBtn: "సేవ్",
    savedBtn: "సేవ్ చేయబడింది",
    aiSummaryHeading: "AI సోర్సింగ్ సారాంశం",
    reqLabel: "మీ అవసరం",
    selSupplierLabel: "ఎంపిక చేసిన సరఫరాదారు",
    priceLabel: "ధర",
    qtyLabel: "పరిమాణము",
    reasonSelLabel: "ఎంపికకు కారణం",
    nextStepLabel: "తదుపరి దశ సిఫార్సు",
    otherOptions: "ఇతర సోర్స్డ్ ఎంపికలు",
    browseSuppliersManually: "సరఫరాదారులను నేరుగా శోధించండి",
    browseDesc: "ధృవీకరించబడిన సరఫరాదారుల డేటాబేస్ ద్వారా వెతకండి మరియు ఫిల్టర్ చేయండి.",
    productSearchLabel: "ఉత్పత్తి శోధన",
    locationCityLabel: "నగరం / ప్రాంతం",
    productCatLabel: "ఉత్పత్తి వర్గం",
    allCategories: "అన్ని వర్గాలు",
    minPriceLabel: "కనీస ధర (₹)",
    maxPriceLabel: "గరిష్ట ధర (₹)",
    minRatingLabel: "కనీస రేటింగ్",
    allRatings: "అన్ని రేటింగ్‌లు",
    availTodayFilter: "ఈరోజు అందుబాటులో ఉన్నవి",
    viewBtn: "చూడండి",
    followBtn: "ఫాలో",
    followingBtn: "ఫాలో అవుతున్నారు",
    noSellersFound: "డైరెక్టరీ శోధనలో సరిపోలే సరఫరాదారులు ఎవరూ కనుగొనబడలేదు.",

    aiSpeaking: "AI మాట్లాడుతోంది",
    connectSupplier: "కనెక్ట్ సప్లయర్",
    askAi: "AIని అడగండి",
    findMore: "మరిన్ని కనుగొనండి",

    step1: "మీ అవసరాన్ని అర్థం చేసుకుంటున్నాము",
    step2: "సరఫరాదారులను శోధిస్తున్నాము",
    step3: "ధరలను సరిపోల్చుతున్నాము",
    step4: "స్టాక్ తనిఖీ చేస్తున్నాము",
    step5: "ఉత్తమ సరఫరాదారుని ఎంచుకుంటున్నాము",
    step6: "సమాధానాన్ని సిద్ధం చేస్తున్నాము",

    connecting: "కనెక్ట్ చేస్తున్నాము...",
    connectingDesc: "సురక్షితమైన కాల్ లైన్లను ఏర్పాటు చేస్తున్నాము మరియు ప్రొఫైల్స్ సింక్ చేస్తున్నాము.",
    connSuccessful: "కనెక్షన్ విజయవంతమైంది",
    yourIdentity: "మీ గుర్తింపు",
    supplierSourced: "సోర్స్ చేసిన సప్లయర్",
    connConnected: "కనెక్ట్ అయింది",
    connSuccessText: "కొనుగోలుదారు మరియు సరఫరాదారు ఇప్పుడు కనెక్ట్ అయ్యారు. మీరు నేరుగా మాట్లాడవచ్చు.",
    callSalesBtn: "సేల్స్ ప్రతినిధికి కాల్ చేయండి",
    doneBtn: "పూర్తయింది",

    activeListings: "క్రియశీల కేటలాగ్ జాబితాలు",
    activeOrders: "క్రియశీల ఆర్డర్లు",
    connectedBuyers: "కనెక్ట్ అయిన కొనుగోలుదారులు",
    revenueLabel: "ఆదాయం",
    salesValue: "నమోదైన విక్రయాల విలువ",
    aiSourcingSug: "AI సోర్సింగ్ సిఫార్సులు",
    inventorySourcingCat: "ఇన్వెంటరీ సోర్సింగ్ కేటలాగ్",
    inventorySourcingDesc: "కస్టమర్ అవసరాలకు సరిపోయే మీ ఉత్పత్తుల వివరాలను నిర్వహించండి.",
    addProduct: "ఉత్పత్తిని జోడించు",
    editProduct: "ఉత్పత్తిని సవరించు",
    deleteProduct: "ఉత్పత్తిని తొలగించు",
    recentConnectedBuyers: "ఇటీవల కనెక్ట్ అయిన కొనుగోలుదారులు",
    recentConnectedDesc: "సురక్షితమైన AI వాయిస్ ద్వారా ఏర్పడిన కాంటాక్ట్‌లు.",
    viewBuyer: "బయ్యర్ వివరాలు",
    contactBuyer: "బయ్యర్‌ను సంప్రదించండి",
    saveChanges: "మార్పులను సేవ్ చేయి",
    cancel: "రద్దు చేయి",
    availableTodayModal: "ఈరోజు అందుబాటులో ఉంది (తక్షణ రవాణా యాక్టివ్‌గా ఉంది)",
    modalAvailable: "అందుబాటులో ఉంది",

    prodNameField: "ఉత్పత్తి పేరు",
    catField: "వర్గం",
    priceField: "ధర",
    qtyField: "పరిమాణము",
    qualityField: "నాణ్యత",
    locField: "నగరం",
    busNameField: "వ్యాపార నామం",
    phoneField: "ఫోన్ నంబర్",
    availabilityField: "అందుబాటు",
    actionsField: "చర్యలు",

    userConsole: "యూజర్ కన్సోల్",
    userConsoleDesc: "మీ వ్యాపార కనెక్షన్లు, యాక్టివిటీ హిస్టరీ మరియు భాషా ప్రాధాన్యతలను నిర్వహించండి.",
    profileIdentity: "ప్రొఫైల్ గుర్తింపు",
    hotlineConnections: "కనెక్షన్ల హాట్‌లైన్",
    recentActivity: "ఇటీవలి కార్యాచరణ",
    consoleSettings: "కన్సోల్ సెట్టింగులు",
    headquarters: "ప్రధాన కార్యాలయం",
    activeCatalogReg: "యాక్టివ్ కేటలాగ్ రిజిస్ట్రీ",
    bothBadge: "రెండు (కొనుగోలుదారు & సరఫరాదారు)",
    procurementManager: "ప్రొక్యూర్మెంట్ & హోల్‌సేల్స్ విభాగం మేనేజర్",
    corporateEmail: "కార్పొరేట్ ఈమెయిల్",
    mobilePhone: "మొబైల్ ఫోన్",
    connHotlineTitle: "వ్యాపార కనెక్షన్ల హాట్‌లైన్",
    connHotlineDesc: "విశ్వసనీయ సరఫరాదారులకు నేరుగా కనెక్ట్ అవ్వండి. సేవ్ చేసిన కాంటాక్ట్‌ల కోసం AI అవసరం లేదు.",
    removeConn: "తొలగించు",
    sendMessage: "సందేశం పంపు",
    buyerActivity: "కొనుగోలుదారు కార్యాచరణ",
    sellerActivity: "సరఫరాదారు కార్యాచరణ",
    recentSearches: "ఇటీవలి శోధనలు",
    recentConversationalLogs: "ఇటీవలి వాయిస్ సంభాషణలు",
    savedSourcedSuppliers: "సేవ్ చేసిన సరఫరాదారులు",
    hotlinePurchaseHistory: "హాట్‌లైన్ కొనుగోలు చరిత్ర",
    connectedBuyerActions: "కనెక్ట్ అయిన బయ్యర్ చర్యలు",
    supplierCatalogChanges: "కేటలాగ్ మార్పులు",
    catalogOrders: "కేటలాగ్ ఆర్డర్లు",
    hotRestockSug: "అవసరమైన స్టాక్ సిఫార్సు",
    systemPref: "వ్యవస్థ ప్రాధాన్యతలు",
    systemPrefDesc: "వాయిస్ ప్రాధాన్యతలు, ఇన్‌పుట్ సెట్టింగులు, థీమ్ మోడ్స్ మరియు నోటిఫికేషన్లను నియంత్రించండి.",
    speechLanguageInterface: "సంభాషణ భాష ఇంటర్‌ఫేస్",
    themeMode: "థీమ్ మోడ్",
    toggleModeTheme: "థీమ్ మార్చండి",
    voiceOutputEngine: "వాయిస్ అవుట్‌పుట్ ఇంజిన్",
    speechMicInput: "మైక్రోఫోన్ ఇన్‌పుట్",
    notificationsCenter: "నోటిఫിക്കేషన్ల సెంటర్",
    notifConnAlerts: "కనెక్షన్ల మార్పుల హెచ్చరికలు",
    notifStockAlerts: "స్టాక్ అప్‌డేట్ల హెచ్చరికలు",

    salesAiAssistant: "సేల్స్ AI అసిస్టెంట్",
    aiBusinessAdvisor: "AI వ్యాపార సలహాదారు",
    askSourcingAdvisor: "సలహాదారుని అడగండి:",
    typeCustomQuestion: "ప్రశ్న టైప్ చేయండి...",
    analyzingSales: "మీ అమ్మకాలను విశ్లేషిస్తున్నాము...",
    salesAiWelcome: "నమస్కారం! నేను మీ సేల్స్ AI అసిస్టెంట్. నేను మీ కేటలాగ్‌ను విశ్లేషించగలను, అవసరాలను అంచనా వేయగలను లేదా వ్యాపార సారాంశాలను సిద్ధం చేయగలను. ప్రారంభించడానికి క్రింది ప్రశ్నలలో ఒకదానిని ఎంచుకోండి:",

    chipSoldToday: "ఈ రోజు ఎన్ని ఉత్పత్తులు అమ్ముడయ్యాయి?",
    chipSellsMost: "ఏ ఉత్పత్తి ఎక్కువగా అమ్ముడవుతోంది?",
    chipRestock: "నేను ఏ ఉత్పత్తిని తిరిగి నిల్వ చేయాలి?",
    chipDecreasing: "అమ్మకాలు ఎందుకు తగ్గుతున్నాయి?",
    chipPricing: "మెరుగైన ధరను సూచించండి.",
    chipTrends: "కస్టమర్ కొనుగోలు ధోరణులను చూపించు.",
    chipInventory: "ఇన్వెంటరీ మెరుగుదలలను సిఫార్సు చేయండి.",
    chipWeekly: "వారపు నివేదికను రూపొందించండి.",
    chipMonthly: "నెలవారీ నివేదికను రూపొందించండి.",
    chipDemand: "డిమాండ్‌ను అంచనా వేయండి.",
    chipBestSelling: "అత్యధికంగా అమ్ముడయ్యే ఉత్పత్తులను సూచించండి.",

    replySoldToday: "ఈ రోజు లాగ్‌ల ఆధారంగా, వర్మ ఫుడ్ ఇండస్ట్రీస్ ₹18,000 విలువైన 150 కిలోల ప్రీమియం పసుపు పొడిని కొనుగోలు చేసింది. మీ ఆర్డర్ పూర్తి దశలో ఉంది.",
    replySellsMost: "మీ కేటలాగ్‌లో అత్యుత్తమ అమ్మకాలు సాధించిన విభాగం పసుపు పొడి. ఈ నెలలో 720 మ్యాచ్‌లతో అత్యధిక కొనుగోలుదారులు దీనిని ఆశ్రయించారు.",
    replyRestock: "మార్కెట్ నివేదికల ప్రకారం పసుపు పొడికి అధిక డిమాండ్ ఉంది. ఈ వారం శోధనలు 22% పెరిగాయి. సరైన నిల్వలు ఉండేలా మరో 2,000 కిలోలు జోడించాల్సిందిగా సిఫార్సు చేస్తున్నాము.",
    replyDecreasing: "ప్రాంతీయ బాస్మతి బియ్యం అమ్మకాలు పెరిగినప్పటికీ, వర్షాల కారణంగా వరంగల్ మరియు చెన్నై జోన్లలో సిమెంట్ మరియు ఉక్కు ఆర్డర్లు 4% తగ్గాయి. పసుపు మరియు బియ్యం అమ్మకాలు స్థిరంగా ఉన్నాయి.",
    replyPricing: "ప్రాంతీయ డిమాండ్ పెరిగినందున, మేము మీ ప్రీమియం పసుపు పొడి ధరను ₹120 నుండి ₹125 కి సర్దుబాటు చేయాల్సిందిగా సూచిస్తున్నాము. ఇది మీ వారపు లాభాలను సుమారు ₹1,500 పెంచుతుంది.",
    replyTrends: "హోల్‌సేల్ వ్యాపారులు పెద్ద పరిమాణంలో ఆర్డర్లు ఇచ్చే ముందు నాణ్యతను పరీక్షించడానికి మొదట చిన్న శాంపిల్ పరిమాణాలు (50 నుండి 200 కిలోలు) కొనుగోలు చేయడానికి ప్రాధాన్యత ఇస్తున్నారు.",
    replyInventory: "ఇన్వెంటరీ సిఫార్సులు:\n1. గ్రేడ్-ఎ సర్టిఫికేషన్ పొందడానికి టేకు కలప నాణ్యత ప్రమాణాలను పెంచండి.\n2. ప్యాకేజింగ్ ఆలస్యం కాకుండా ఉండటానికి షిప్పింగ్ కార్టన్‌లను కనీసం 5,000 స్టాక్‌లో ఉంచండి.",
    replyWeekly: "వారపు పనితీరు సారాంశం (05 జూలై 2026):\n• సక్రియ జాబితాలు: 2 ఉత్పత్తులు\n• కనెక్ట్ అయిన బయ్యర్లు: 128 మంది\n• మొత్తం ఆదాయం: ₹1.85 లక్షలు\n• ఆర్డర్ల వృద్ధి: +12% పెరుగుదల\n• నమ్మక రేటింగ్: 4.8★",
    replyMonthly: "నెలవారీ సోర్సింగ్ నివేదిక:\n• శోధనల సంఖ్య: 1,420 హిట్లు\n• విజయవంతమైన కనెక్షన్లు: 128 సంప్రదింపులు\n• గరిష్ట విక్రయాలు: పసుపు, సోనా మసూరి బియ్యం\n• నెలవారీ వృద్ధి రేటు: +14.5% MoM",
    replyDemand: "డిమాండ్ అంచనా (రాబోయే 30 రోజులు):\n• పసుపు సోర్సింగ్: చాలా ఎక్కువ (+18% అంచనా)\n• బియ్యం సోర్సింగ్: స్థిరంగా ఉంది (+6% అంచనా)\n• సిమెంట్/ఉక్కు: స్వల్ప వృద్ధి (+4% హైదరాబాద్‌లో)",
    replyBestSelling: "దక్షిణ భారతదేశంలో అత్యధికంగా అమ్ముడవుతున్న ఉత్పత్తులలో ఈరోడ్ ఆర్గానిక్ పసుపు పొడి, నెల్లూరు సోనా మసూరి బియ్యం మరియు భూకంప నిరోధక TMT స్టీల్ రాడ్లు ఉన్నాయి.",
    replyGeneric: "నమస్కారం! నేను మీ ప్రశ్నను విశ్లేషించాను. మీ కేటలాగ్‌లో ఉన్న ఉత్పత్తుల ఆధారంగా, కొనుగోలుదారుల ఆర్డర్లను వెంటనే అందుకోవడానికి స్టాక్ సిద్ధంగా ఉంచుకోవడం ముఖ్యం. మరిన్ని వివరాల కోసం అడగండి!",
    aiBusinessInsights: "AI వ్యాపార అంతర్దృష్టులు",
    highDemandTitle: "🔥 కొనుగోలుదారుల అధిక డిమాండ్",
    highDemandDesc: "{Product} ఈ వారం అనేక కొనుగోలుదారుల శోధనలను పొందింది. అందుబాటులో ఉన్న స్టాక్‌ను పెంచడాన్ని పరిశీలించండి.",
    lowStockTitle: "📦 తక్కువ స్టాక్ అలర్ట్",
    lowStockDesc: "{Product} స్టాక్ అయిపోవస్తోంది. కొనుగోలుదారుల మ్యాచ్‌లను పొందడం కొనసాగించడానికి త్వరలోనే రీస్టాక్ చేయండి.",
    pricingTitle: "💰 ధర సిఫార్సు",
    pricingDesc: "ఇతర సరఫరాదారులతో పోలిస్తే మీ {Product} ధర కొంచెం ఎక్కువగా ఉంది. ధరను కిలోకు ₹5 తగ్గించడం వల్ల కొనుగోలుదారుల ఆసక్తి పెరుగుతుంది.",
    bestSellingTitle: "⭐ అత్యధికంగా అమ్ముడైన ఉత్పత్తి",
    bestSellingDesc: "{Product} ఈ నెలలో అత్యధిక ఆదాయాన్ని ఆర్జించింది. ఈ ఉత్పత్తిని ప్రచారం చేయడాన్ని పరిశీలించండి.",
    demandForecastTitle: "📈 డిమాండ్ సూచన",
    demandForecastDesc: "ఇటీవలి శోధనల ఆధారంగా వచ్చే వారం {Product} డిమాండ్ పెరుగుతుందని అంచనా వేయబడింది.",
    regionalTrendTitle: "📍 ప్రాంతీయ ట్రెండ్",
    regionalTrendDesc: "ప్రస్తుతం హైదరాబాద్‌లో నిర్మాణ సామగ్రి అత్యంత వేగంగా అభివృద్ధి చెందుతున్న విభాగంగా ఉంది."
  },
  Hindi: {
    buyerDashboard: "बायर्स डैशबोर्ड",
    sellerDashboard: "सेलर्स डैशबोर्ड",
    userDashboard: "यूजर डैशबोर्ड",
    home: "होम",
    profile: "प्रोफाइल",
    notifications: "सूचनाएं",
    buyerAccount: "खरीदार खाता",
    langChangedToast: "भाषा हिन्दी में बदल दी गई।",
    allRead: "सभी पढ़े हुए चिह्नित करें",
    notifCenter: "सूचना केंद्र",
    logout: "लॉग आउट",

    heroHeading: "सप्लाई मार्केट",
    heroSubtitle: "AI सप्लायर मैच और कॉल कनेक्ट प्लेटफॉर्म",
    heroDesc: "सप्लाई मार्केट आर्टिफिशियल इंटेलिजेंस का उपयोग करके खरीदारों को विश्वसनीय आपूर्तिकर्ताओं को जल्दी खोजने में मदद करता है। AI आपकी आवश्यकता को समझता है, सबसे अच्छा आपूर्तिकर्ता ढूंढता है और आपको तेजी से जोड़ने में मदद करता है।",
    goToBuyer: "बायर्स डैशबोर्ड पर जाएं",
    goToSeller: "सेलर्स डैशबोर्ड पर जाएं",
    howItWorks: "सप्लाई मार्केट कैसे काम करता है",
    howDesc: "आपकी आवश्यकताओं को सुरक्षित सीधे कॉल में बदलने वाले चार आसान चरण।",
    whyChoose: "सप्लाई मार्केट क्यों चुनें",
    whyDesc: "व्यवसायों के बीच विश्वास बनाने के लिए डिज़ाइन किया गया एक प्रीमियम, सरल व्यापार मंच।",
    step1Title: "आवश्यकता बताएं",
    step1Desc: "अपनी मात्रा, गुणवत्ता और स्थान को टेक्स्ट या वॉयस निर्देशों में समझाएं।",
    step2Title: "AI सर्वोत्तम सप्लायर खोजेगा",
    step2Desc: "हमारा मिलान इंजन कैटलॉग खोजता है और सबसे उपयुक्त आपूर्तिकर्ताओं को ग्रेड करता है।",
    step3Title: "आपूर्तिकर्ता विवरण की समीक्षा करें",
    step3Desc: "रुपये में कीमतें, स्टॉक बफर, स्थान और रेटिंग की तुलना करें।",
    step4Title: "सीधे जुड़ें",
    step4Desc: "चर्चा शुरू करने के लिए सुरक्षित टेलीफोन डायलर कनेक्शन का उपयोग करें।",
    feat1Title: "तेजी से सप्लायर की खोज",
    feat1Desc: "उपयुक्त आपूर्तिकर्ताओं को तुरंत खोजें। घंटों बाजार कॉल करने का समय बचाएं।",
    feat2Title: "विश्वसनीय व्यवसाय",
    feat2Desc: "केवल उच्च विश्वास स्कोर और अच्छे प्रदर्शन वाली सत्यापित कंपनियों से जुड़ें।",
    feat3Title: "AI वॉयस असिस्टेंट",
    feat3Desc: "संवादात्मक वॉयस असिस्टेंट मिलान विवरणों को सहजता से सुनाता है।",
    feat4Title: "कई भाषाएं",
    feat4Desc: "हिन्दी, तेलुगु, तमिल, कन्नाड, मलयालम और अंग्रेजी: 6 भारतीय भाषाओं में बोलें और निर्देश प्राप्त करें।",
    feat5Title: "स्मार्ट सिफारिशें",
    feat5Desc: "AI स्पष्ट कारण बताता है कि प्रत्येक विकल्प आपके लिए सबसे उपयुक्त क्यों है।",
    feat6Title: "व्यावसायिक कनेक्शन",
    feat6Desc: "संपर्क सहेजें और बार-बार व्यापार करने के लिए कंपनी निर्देशिकाओं को फॉलो करें।",

    findRightSupplier: "सही आपूर्तिकर्ता खोजें",
    tellUsNeed: "हमें बताएं कि आपको क्या चाहिए। हमारा AI आपको सबसे अच्छा आपूर्तिकर्ता खोजने में मदद करेगा।",
    searchPlaceholder: 'उदाहरण: "मुझे अपने हर्बल उत्पादों के व्यवसाय के लिए 100 किलोग्राम प्रीमियम हल्दी चाहिए।"',
    speakBtn: "बोलें",
    findSuppliersBtn: "आपूर्तिकर्ता खोजें",
    clearBtn: "साफ करें",
    listeningLabel: "सुन रहे हैं। अपनी आवश्यकता बोलें...",
    matchingSuppliers: "आपूर्तिकर्ताओं का मिलान कर रहे हैं...",
    popularSearches: "लोकप्रिय खोजें:",
    processingHeuristics: "मिलान विधियों को संसाधित कर रहे हैं",
    processingDesc: "इन्वेंट्री डेटाबेस और वितरण मार्गों का विश्लेषण कर रहे हैं।",
    aiRecomHeading: "AI सिफारिश चयन",
    bestMatch: "सर्वोत्तम मिलान",
    ratingLabel: "रेटिंग",
    locationLabel: "स्थान",
    availToday: "आज उपलब्ध है",
    matchScore: "मैच स्कोर",
    reasonForRecom: "सिफारिश का कारण:",
    productOfferPrice: "उत्पाद की पेशकश मूल्य",
    connectBtn: "कनेक्ट",
    viewDetailsBtn: "विवरण देखें",
    saveBtn: "सहेजें",
    savedBtn: "सहेजा गया",
    aiSummaryHeading: "AI सोर्सिंग सारांश",
    reqLabel: "आपकी आवश्यकता",
    selSupplierLabel: "चयनित आपूर्तिकर्ता",
    priceLabel: "कीमत",
    qtyLabel: "मात्रा",
    reasonSelLabel: "चयन का कारण",
    nextStepLabel: "अगले कदम की सिफारिश",
    otherOptions: "अन्य सोर्स किए गए विकल्प",
    browseSuppliersManually: "आपूर्तिकर्ताओं को मैन्युअल रूप से खोजें",
    browseDesc: "सत्यापित आपूर्तिकर्ताओं के डेटाबेस में खोजें और फ़िल्टर करें।",
    productSearchLabel: "उत्पाद खोज",
    locationCityLabel: "शहर / स्थान",
    productCatLabel: "उत्पाद श्रेणी",
    allCategories: "सभी श्रेणियां",
    minPriceLabel: "न्यूनतम मूल्य (₹)",
    maxPriceLabel: "अधिकतम मूल्य (₹)",
    minRatingLabel: "न्यूनतम रेटिंग",
    allRatings: "सभी रेटिंग",
    availTodayFilter: "आज उपलब्ध",
    viewBtn: "देखें",
    followBtn: "फॉलो",
    followingBtn: "फॉलो कर रहे हैं",
    noSellersFound: "मैन्युअल निर्देशिका खोज में कोई मिलान आपूर्तिकर्ता नहीं मिला।",

    aiSpeaking: "AI बोल रहा है",
    connectSupplier: "कॉल कनेक्ट",
    askAi: "AI से पूछें",
    findMore: "और खोजें",

    step1: "आपकी आवश्यकता को समझ रहे हैं",
    step2: "आपूर्तिकर्ताओं की खोज कर रहे हैं",
    step3: "कीमतों की तुलना कर रहे हैं",
    step4: "स्टॉक की जांच कर रहे हैं",
    step5: "सर्वश्रेष्ठ आपूर्तिकर्ता चुन रहे हैं",
    step6: "जवाब तैयार कर रहे हैं",

    connecting: "कनेक्ट कर रहे हैं...",
    connectingDesc: "सुरक्षित कॉल लाइनों को स्थापित कर रहे हैं और प्रोफाइल सिंक कर रहे हैं।",
    connSuccessful: "कनेक्शन सफल रहा",
    yourIdentity: "आपकी पहचान",
    supplierSourced: "सोर्स किया गया सप्लायर",
    connConnected: "जुड़ गया",
    connSuccessText: "खरीदार और आपूर्तिकर्ता अब जुड़े हुए हैं। आप सीधे अपनी बातचीत जारी रख सकते हो।",
    callSalesBtn: "बिक्री प्रतिनिधि को कॉल करें",
    doneBtn: "पूर्ण",

    activeListings: "सक्रिय कैटलॉग सूची",
    activeOrders: "सक्रिय ऑर्डर",
    connectedBuyers: "जुड़े हुए खरीदार",
    revenueLabel: "राजस्व",
    salesValue: "दर्ज की गई बिक्री मूल्य",
    aiSourcingSug: "AI सोर्सिंग सिफारिशें",
    inventorySourcingCat: "इन्वेंट्री सोर्सिंग कैटलॉग",
    inventorySourcingDesc: "ग्राहक की जरूरतों से मेल खाने वाले अपने उत्पादों का विवरण प्रबंधित करें।",
    addProduct: "उत्पाद जोड़ें",
    editProduct: "उत्पाद संपादित करें",
    deleteProduct: "उत्पाद हटाएं",
    recentConnectedBuyers: "हाल ही में जुड़े खरीदार",
    recentConnectedDesc: "सुरक्षित AI वॉयस कॉल के माध्यम से स्थापित संपर्क विवरण।",
    viewBuyer: "बायर्स विवरण",
    contactBuyer: "बायर्स से संपर्क करें",
    saveChanges: "बदलाव सहेजें",
    cancel: "रद्द करें",
    availableTodayModal: "आज उपलब्ध है (तत्काल शिपिंग सक्रिय)",
    modalAvailable: "उपलब्ध",

    prodNameField: "उत्पाद का नाम",
    catField: "श्रेणी",
    priceField: "कीमत",
    qtyField: "मात्रा",
    qualityField: "गुणवत्ता",
    locField: "शहर",
    busNameField: "व्यापार नाम",
    phoneField: "फोन नंबर",
    availabilityField: "उपलब्धता",
    actionsField: "कार्रवाई",

    userConsole: "यूजर कंसोल",
    userConsoleDesc: "अपने व्यावसायिक कनेक्शन, गतिविधि इतिहास और भाषा प्राथमिकताओं को प्रबंधित करें।",
    profileIdentity: "प्रोफाइल पहचान",
    hotlineConnections: "कनेक्शन हॉटलाइन",
    recentActivity: "हाल की गतिविधि",
    consoleSettings: "कंसोल सेटिंग्स",
    headquarters: "मुख्यालय",
    activeCatalogReg: "सक्रिय कैटलॉग रजिस्ट्री",
    bothBadge: "दोनों (खरीदार और आपूर्तिकर्ता)",
    procurementManager: "प्रोक्योरमेंट और थोक विभाग प्रबंधक",
    corporateEmail: "कॉर्पोरेट ईमेल",
    mobilePhone: "मोबाइल फोन",
    connHotlineTitle: "व्यावसायिक कनेक्शन हॉटलाइन",
    connHotlineDesc: "विश्वसनीय आपूर्तिकर्ताओं से सीधे जुड़ें। सहेजे गए संपर्कों के लिए AI की आवश्यकता नहीं है।",
    removeConn: "हटाएं",
    sendMessage: "संदेस भेजें",
    buyerActivity: "खरीदार गतिविधि",
    sellerActivity: "आपूर्तिकर्ता गतिविधि",
    recentSearches: "हाल की खोजें",
    recentConversationalLogs: "हाल के संवादात्मक ऑडियो लॉग",
    savedSourcedSuppliers: "सहेजे गए आपूर्तिकर्ता",
    hotlinePurchaseHistory: "हॉटलाइन खरीद इतिहास",
    connectedBuyerActions: "जुड़े हुए खरीदार की गतिविधियाँ",
    supplierCatalogChanges: "कैटलॉग परिवर्तन",
    catalogOrders: "कैटलॉग ऑर्डर",
    hotRestockSug: "आवश्यक स्टॉक सुझाव",
    systemPref: "सिस्टम प्राथमिकताएं",
    systemPrefDesc: "वॉयस प्राथमिकताएं, इनपुट सेटिंग्स, थीम मोड और सूचनाएं नियंत्रित करें।",
    speechLanguageInterface: "भाषण भाषा इंटरफ़ेस",
    themeMode: "theme mode",
    toggleModeTheme: "थीम बदलें",
    voiceOutputEngine: "वॉयस आउटपुट इंजन",
    speechMicInput: "माइक्रोफ़ोन इनपुट",
    notificationsCenter: "सूचना केंद्र",
    notifConnAlerts: "कनेक्शन परिवर्तनों की चेतावनी",
    notifStockAlerts: "स्टॉक अपडेट की चेतावनी",

    salesAiAssistant: "सेल्स AI असिस्टेंट",
    aiBusinessAdvisor: "AI व्यापार सलाहकार",
    askSourcingAdvisor: "सलाहकार से पूछें:",
    typeCustomQuestion: "प्रश्न टाइप करें...",
    analyzingSales: "आपकी बिक्री का विश्लेषण कर रहे हैं...",
    salesAiWelcome: "नमस्ते! मैं आपका सेल्स AI असिस्टेंट हूं। मैं आपके कैटलॉग का विश्लेषण कर सकता हूं, मांग का अनुमान लगा सकता हूं, या व्यापार रिपोर्ट तैयार कर सकता हूं। शुरू करने के लिए नीचे दिए गए प्रश्नों में से एक चुनें:",

    chipSoldToday: "आज कितने उत्पाद बिके?",
    chipSellsMost: "कौन सा उत्पाद सबसे ज्यादा बिकता है?",
    chipRestock: "मुझे कौन सा उत्पाद फिर से स्टॉक करना चाहिए?",
    chipDecreasing: "बिक्री क्यों घट रही है?",
    chipPricing: "बेहतर मूल्य का सुझाव दें।",
    chipTrends: "ग्राहक खरीद रुझान दिखाएं।",
    chipInventory: "इन्वेंट्री सुधारों की सिफारिश करें।",
    chipWeekly: "साप्ताहिक सारांश रिपोर्ट जनरेट करें।",
    chipMonthly: "मासिक रिपोर्ट जनरेट करें।",
    chipDemand: "मांग का अनुमान लगाएं।",
    chipBestSelling: "सबसे ज्यादा बिकने वाले उत्पादों का सुझाव दें।",

    replySoldToday: "आज के लॉग के आधार पर, वर्मा फूड इंडस्ट्रीज ने ₹18,000 मूल्य की 150 किलोग्राम प्रीमियम हल्दी पाउडर खरीदी। आपका ऑर्डर पूरा हो चुका है।",
    replySellsMost: "आपके कैटलॉग में सबसे अच्छा प्रदर्शन हल्दी पाउडर का है। इस महीने 720 खरीदार मिलानों के साथ यह पहले स्थान पर रहा है।",
    replyRestock: "थोक मांग के विश्लेषण से पता चलता है कि हल्दी पाउडर की मांग काफी अधिक है। इस हफ्ते खोजें 22% बढ़ी हैं। हम बफर स्टॉक बनाए रखने के लिए 2,000 किलोग्राम और जोड़ने की सलाह देते हैं।",
    replyDecreasing: "क्षेत्रीय बासमती चावल की बिक्री में वृद्धि के बावजूद, बारिश के कारण वारंगल और चेन्नई क्षेत्रों में सीमेंट और लोहे की मांग में 4% की गिरावट आई है। हल्दी और चावल की बिक्री मजबूत है।",
    replyPricing: "क्षेत्रीय मांग में वृद्धि के कारण, हम हल्दी पाउडर की कीमत ₹120 से बढ़ाकर ₹125 प्रति किलोग्राम करने का सुझाव देते हैं। इससे बिना मिलान प्रभावित किए आपका साप्ताहिक लाभ ₹1,500 बढ़ जाएगा।",
    replyTrends: "थोक व्यापारी बड़े ऑर्डर फाइनल करने से पहले गुणवत्ता की जांच के लिए शुरू में छोटे नमूने (50 से 200 किलोग्राम) खरीदने को प्राथमिकता दे रहे हैं।",
    replyInventory: "इन्वेंट्री सिफारिशें:\n1. ग्रेड-ए प्रमाणीकरण के लिए सागौन की लकड़ी के गुणवत्ता मानकों में सुधार करें।\n2. पैकेजिंग देरी से बचने के लिए कार्टन स्टॉक को हमेशा 5,000 से ऊपर बनाए रखें।",
    replyWeekly: "साप्ताहिक प्रदर्शन रिपोर्ट (05 जुलाई 2026):\n• सक्रिय सूचियां: 2 उत्पाद\n• जुड़े खरीदार: 128\n• कुल राजस्व: ₹1.85 लाख\n• ऑर्डर दर में वृद्धि: +12%\n• ट्रस्ट रेटिंग: 4.8★",
    replyMonthly: "मासिक सोर्सिंग रिपोर्ट:\n• खोज संख्या: 1,420 हिट्स\n• सफल कनेक्शन: 128\n• शीर्ष श्रेणियां: हल्दी, सोना मसूरी चावल\n• मासिक विकास दर: +14.5% MoM",
    replyDemand: "मांग का पूर्वानुमान (अगले 30 दिन):\n• हल्दी सोर्सिंग: बहुत अधिक (+18% अनुमानित)\n• चावल सोर्सिंग: स्थिर (+6% अनुमानित)\n• सीमेंट/लोहा: मध्यम वृद्धि (+4% हैदराबाद में)",
    replyBestSelling: "दक्षिण भारत में सबसे अधिक बिकने वाले उत्पादों में इरोड की जैविक हल्दी, नेल्लोर का सोना मसूरी चावल और भूकंप प्रतिरोधी TMT सरिये शामिल हैं।",
    replyGeneric: "नमस्ते! मैंने आपके प्रश्न का विश्लेषण किया है। आपके कैटलॉग उत्पादों के आधार पर, ऑर्डर प्राप्त करने के लिए स्टॉक तुरंत तैयार रखना सबसे महत्वपूर्ण है। अधिक विवरण के लिए पूछें!",
    aiBusinessInsights: "AI व्यावसायिक अंतर्दृष्टि",
    highDemandTitle: "🔥 उच्च खरीदार मांग",
    highDemandDesc: "इस सप्ताह {Product} के लिए कई खरीदार खोजें प्राप्त हुई हैं। उपलब्ध स्टॉक बढ़ाने पर विचार करें।",
    lowStockTitle: "📦 कम स्टॉक चेतावनी",
    lowStockDesc: "{Product} का स्टॉक कम हो रहा है। खरीदार मिलान प्राप्त करना जारी रखने के लिए जल्द ही रीस्टॉक करें।",
    pricingTitle: "💰 मूल्य निर्धारण सिफारिश",
    pricingDesc: "समान आपूर्तिकर्ताओं की तुलना में आपकी {Product} की कीमत थोड़ी अधिक है। कीमत में ₹5 प्रति {Unit} की कटौती करने से खरीदार की रुचि बढ़ सकती है।",
    bestSellingTitle: "⭐ सबसे ज्यादा बिकने वाला उत्पाद",
    bestSellingDesc: "{Product} ने इस महीने सबसे अधिक राजस्व उत्पन्न किया। इस उत्पाद को बढ़ावा देने पर विचार करें।",
    demandForecastTitle: "📈 मांग का पूर्वानुमान",
    demandForecastDesc: "हाल की खोजों के आधार पर अगले सप्ताह {Product} के लिए खरीदार की रुचि बढ़ने की उम्मीद है।",
    regionalTrendTitle: "📍 क्षेत्रीय प्रवृत्ति",
    regionalTrendDesc: "निर्माण सामग्री वर्तमान में हैदराबाद में सबसे तेजी से बढ़ता हुआ वर्ग है।"
  },
  Tamil: {
    buyerDashboard: "வாங்குபவர் டாஷ்போர்டு",
    sellerDashboard: "விற்பனையாளர் டாஷ்போர்டு",
    userDashboard: "பயனர் டாஷ்போர்டு",
    home: "முகப்பு",
    profile: "சுயவிவரம்",
    notifications: "அறிவிப்புகள்",
    buyerAccount: "வாங்குபவர் கணக்கு",
    langChangedToast: "மொழி தமிழுக்கு மாற்றப்பட்டது.",
    allRead: "அனைத்தையும் படித்ததாகக் குறிக்கவும்",
    notifCenter: "அறிவிப்பு மையம்",
    logout: "வெளியேறு",

    heroHeading: "சப்ளை மார்க்கெட்",
    heroSubtitle: "AI சப்ளையர் மேட்ச் & கால் கனெக்ட் தளம்",
    heroDesc: "செயற்கை நுண்ணறிவைப் பயன்படுத்தி வாங்குபவர்கள் நம்பகமான சப்ளையர்களை விரைவாகக் கண்டறிய சப்ளை மார்க்கெட் உதவுகிறது. AI உங்கள் தேவையைப் புரிந்துகொண்டு, சிறந்த சப்ளையரைக் கண்டுபிடித்து, விரைவாக இணைக்க உதவுகிறது.",
    goToBuyer: "வாங்குபவர் டாஷ்போர்டுக்குச் செல்லவும்",
    goToSeller: "விற்பனையாளர் டாஷ்போர்டுக்குச் செல்லவும்",
    howItWorks: "சப்ளை மார்க்கெட் எவ்வாறு செயல்படுகிறது",
    howDesc: "உங்கள் தேவைகளைப் பாதுகாப்பான நேரடி அழைப்புகளாக மாற்றும் நான்கு எளிய படிகள்.",
    whyChoose: "சப்ளை மார்க்கெட்டை ஏன் தேர்வு செய்ய வேண்டும்",
    whyDesc: "வணிகங்களுக்கு இடையே நம்பிக்கையை உருவாக்க வடிவமைக்கப்பட்ட ஒரு பிரீமியம், எளிய வர்த்தக தளம்.",
    step1Title: "தேவையை விவரிக்கவும்",
    step1Desc: "உங்கள் அளவு, தரம் மற்றும் இருப்பிடத்தை உரை அல்லது குரல் வழிமுறைகளில் விளக்கவும்.",
    step2Title: "AI சிறந்த சப்ளையரைக் கண்டறியும்",
    step2Desc: "எங்கள் மேட்சிங் இயந்திரம் சப்ளையர்களைத் தேடி, மிகவும் பொருத்தமானவர்களைத் தരം பிரிக்கிறது.",
    step3Title: "சப்ளையர் विवरणங்களை மதிப்பாய்வு செய்யவும்",
    step3Desc: "ரூபாயில் விலைகள், இருப்பு அளவு, இருப்பிடம் மற்றும் மதிப்பீடுகளை ஒப்பிடுக.",
    step4Title: "நேரடியாக இணைக்கவும்",
    step4Desc: "உரையாடலைத் தொடங்க பாதுகாப்பான தொலைபேசி டயலர் இணைப்புகளைப் பயன்படுத்தவும்.",
    feat1Title: "வேகமான சப்ளையர் கண்டுபிடிப்பு",
    feat1Desc: "பொருத்தமான சப்ளையர்களை உடனடியாகக் கண்டறியவும். கைமுறையாக அழைப்புகள் செய்வதற்கான நேரத்தை மிச்சப்படுத்துங்கள்.",
    feat2Title: "நம்பகமான வணிகங்கள்",
    feat2Desc: "உயர் நம்பிக்கை மதிப்பெண்கள் மற்றும் நல்ல செயல்திறன் கொண்ட சான்றளிக்கப்பட்ட நிறுவனங்களுடன் மட்டுமே இணையுங்கள்.",
    feat3Title: "AI குரல் உதவியாளர்",
    feat3Desc: "உரையாடல் குரல் உதவியாளர் மேட்சிங் விவரங்களை எளிதாகக் கேட்கச் செய்கிறது.",
    feat4Title: "பல்வேறு மொழிகள்",
    feat4Desc: "தமிழ், தெலுங்கு, இந்தி, கன்னடம், மலையாளம் மற்றும் ஆங்கிலம்: 6 இந்திய மொழிகளில் பேசவும் வழிமுறைகளைப் பெறவும்.",
    feat5Title: "ஸ்மார்ட் பரிந்துரைகள்",
    feat5Desc: "ஒவ்வொரு தேர்வும் உங்களுக்கு ஏன் மிகவும் பொருத்தமானது என்பதற்கான தெளிவான காரணங்களை AI விளக்குகிறது.",
    feat6Title: "வணிக தொடர்புகள்",
    feat6Desc: "தொடர்புகளைச் சேமித்து, மீண்டும் வர்த்தகம் செய்ய நிறுவனத்தின் கோப்பகங்களைப் பின்தொடரவும்.",

    findRightSupplier: "சரியான சப்ளையரைக் கண்டறியவும்",
    tellUsNeed: "உங்களுக்கு என்ன தேவை என்று எங்களிடம் கூறுங்கள். சிறந்த சப்ளையரைக் கண்டறிய எங்கள் AI உதவும்.",
    searchPlaceholder: 'எடுத்துக்காட்டு: "எனது மூலிகை தயாரிப்புகள் வணிகத்திற்காக எனக்கு 100 கிலோ பிரீமியம் மஞ்சள் தூள் தேவை."',
    speakBtn: "பேசவும்",
    findSuppliersBtn: "சப்ளையர்களைக் கண்டறியவும்",
    clearBtn: "அழிக்க",
    listeningLabel: "கேட்கிறது. உங்கள் தேவையைப் பேசவும்...",
    matchingSuppliers: "சப்ளையர்களைப் பொருத்துகிறோம்...",
    popularSearches: "பிரபலமான தேடல்கள்:",
    processingHeuristics: "மேட்சிங் முறைகளைச் செயலாக்குகிறோம்",
    processingDesc: "இருப்பு தரவுத்தளங்கள் மற்றும் விநியோக வழிகளை பகுப்பாய்வு செய்கிறோம்.",
    aiRecomHeading: "AI பரிந்துரை தேர்வு",
    bestMatch: "சிறந்த பொருத்தம்",
    ratingLabel: "மதிப்பீடு",
    locationLabel: "இருப்பிடம்",
    availToday: "இன்று கிடைக்கும்",
    matchScore: "பொருத்த மதிப்பெண்",
    reasonForRecom: "பரிந்துரைக்கான காரணம்:",
    productOfferPrice: "தயாரிப்பு சலுகை விலை",
    connectBtn: "இணைக்கவும்",
    viewDetailsBtn: "விவரங்களை பார்க்க",
    saveBtn: "சேமிக்கவும்",
    savedBtn: "சேமிக்கப்பட்டது",
    aiSummaryHeading: "AI சோர்சிங் சுருக்கம்",
    reqLabel: "உங்கள் தேவை",
    selSupplierLabel: "தேர்ந்தெடுக்கப்பட்ட சப்ளையர்",
    priceLabel: "விலை",
    qtyLabel: "அளவு",
    reasonSelLabel: "தேர்வுக்கான காரணம்",
    nextStepLabel: "அடுத்த படி பரிந்துரை",
    otherOptions: "இதர சோர்ஸ் செய்யப்பட்ட விருப்பங்கள்",
    browseSuppliersManually: "சப்ளையர்களை கைமுறையாக தேடுங்கள்",
    browseDesc: "சரிபார்க்கப்பட்ட சப்ளையர்களின் தரவுத்தளத்தில் தேடவும் மற்றும் வடிகட்டவும்.",
    productSearchLabel: "தயாரிப்பு தேடல்",
    locationCityLabel: "நகரம் / இருப்பிடம்",
    productCatLabel: "தயாரிப்பு வகை",
    allCategories: "அனைத்து பிரிவுகள்",
    minPriceLabel: "குறைந்தபட்ச விலை (₹)",
    maxPriceLabel: "அதிகபட்ச விலை (₹)",
    minRatingLabel: "குறைந்தபட்ச மதிப்பீடு",
    allRatings: "அனைத்து மதிப்பீடுகள்",
    availTodayFilter: "இன்று கிடைக்கும்",
    viewBtn: "பார்க்க",
    followBtn: "பின்தொடர",
    followingBtn: "பின்தொடர்கிறீர்கள்",
    noSellersFound: "கைமுறை கோப்பகத் தேடலில் பொருத்தமான சப்ளையர்கள் யாரும் கண்டறியப்படவில்லை.",

    aiSpeaking: "AI பேசுகிறது",
    connectSupplier: "சப்ளையரை இணைக்கவும்",
    askAi: "AIயிடம் கேட்கவும்",
    findMore: "மேலும் தேட",

    step1: "உங்கள் தேவையைப் புரிந்துகொள்கிறோம்",
    step2: "சப்ளையர்களைத் தேடுகிறோம்",
    step3: "விலைகளை ஒப்பிடுகிறோம்",
    step4: "இருப்பைச் சரிபார்க்கிறோம்",
    step5: "சிறந்த சப்ளையரைத் தேர்வுசெய்கிறோம்",
    step6: "பதிலைத் தயார் செய்கிறோம்",

    connecting: "இணைக்கிறது...",
    connectingDesc: "பாதுகாப்பான அழைப்பு வரிகளை நிறுவி, சுயவிவரங்களை ஒத்திசைக்கிறோம்.",
    connSuccessful: "இணைப்பு வெற்றிகரமாக முடிந்தது",
    yourIdentity: "உங்கள் அடையாளம்",
    supplierSourced: "சோர்ஸ் செய்யப்பட்ட சப்ளையர்",
    connConnected: "இணைக்கப்பட்டது",
    connSuccessText: "வாங்குபவரும் சப்ளையரும் இப்போது இணைக்கப்பட்டுள்ளனர். நீங்கள் நேரடியாகப் பேசலாம்.",
    callSalesBtn: "விற்பனை பிரதிநிதியை அழைக்கவும்",
    doneBtn: "முடிந்தது",

    activeListings: "செயலில் உள்ள தயாரிப்பு பட்டியல்கள்",
    activeOrders: "செயலில் உள்ள ஆர்டர்கள்",
    connectedBuyers: "இணைக்கப்பட்ட வாங்குபவர்கள்",
    revenueLabel: "வருவாய்",
    salesValue: "பதிவு செய்யப்பட்ட விற்பனை மதிப்பு",
    aiSourcingSug: "AI சோர்சிங் பரிந்துரைகள்",
    inventorySourcingCat: "இருப்பு சோர்சிங் பட்டியல்",
    inventorySourcingDesc: "வாடிக்கையாளர் தேவைகளுக்குப் பொருந்தக்கூடிய உங்கள் தயாரிப்புகளின் விவரங்களை நிர்வகிக்கவும்.",
    addProduct: "தயாரிப்பைச் சேர்",
    editProduct: "தயாரிப்பைத் திருத்து",
    deleteProduct: "தயாரிப்பை நீக்கு",
    recentConnectedBuyers: "சமீபத்தில் இணைக்கப்பட்ட வாங்குபவர்கள்",
    recentConnectedDesc: "பாதுகாப்பான AI குரல் அழைப்புகள் மூலம் நிறுவப்பட்ட தொடர்பு விவரங்கள்.",
    viewBuyer: "வாங்குபவர் விவரங்கள்",
    contactBuyer: "வாங்குபவரைத் தொடர்பு கொள்ளவும்",
    saveChanges: "மாற்றங்களைச் சேமிக்கவும்",
    cancel: "ரத்து செய்",
    availableTodayModal: "இன்று கிடைக்கும் (உடனடி அனுப்புதல் செயலில் உள்ளது)",
    modalAvailable: "கிடைக்கும்",

    prodNameField: "தயாரிப்பு பெயர்",
    catField: "வகை",
    priceField: "விலை",
    qtyField: "அளவு",
    qualityField: "தரம்",
    locField: "நகரம்",
    busNameField: "வணிகப் பெயர்",
    phoneField: "தொலைபேசி எண்",
    availabilityField: "இருப்பு",
    actionsField: "செயல்கள்",

    userConsole: "பயனர் கன்சோல்",
    userConsoleDesc: "உங்கள் வணிக தொடர்புகள், செயல்பாட்டு வரலாறு மற்றும் மொழி விருப்பங்களை நிர்வகிக்கவும்.",
    profileIdentity: "சுயவிவர அடையாளம்",
    hotlineConnections: "தொடர்பு ஹாட்லைன்",
    recentActivity: "சமீபத்திய செயல்பாடு",
    consoleSettings: "கன்சோல் அமைப்புகள்",
    headquarters: "தலைமையகம்",
    activeCatalogReg: "செயலில் உள்ள தயாரிப்பு பதிவேடு",
    bothBadge: "இரண்டும் (வாங்குபவர் & விற்பனையாளர்)",
    procurementManager: "கொள்முதல் & மொத்த விற்பனை பிரிவு மேலாளர்",
    corporateEmail: "நிறுவன மின்னஞ்சல்",
    mobilePhone: "கைபேசி எண்",
    connHotlineTitle: "வணிக தொடர்பு ஹாட்லைன்",
    connHotlineDesc: "நம்பகமான சப்ளையர்களுடன் நேரடியாக இணையுங்கள். சேமித்த தொடர்புகளுக்கு AI தேவையில்லை.",
    removeConn: "நீக்கு",
    sendMessage: "செய்தி அனுப்பு",
    buyerActivity: "வாங்குபவர் செயல்பாடு",
    sellerActivity: "விற்பனையாளர் செயல்பாடு",
    recentSearches: "சமீபத்திய தேடல்கள்",
    recentConversationalLogs: "சமீபத்திய குரல் உரையாடல்கள்",
    savedSourcedSuppliers: "சேமிக்கப்பட்ட சப்ளையர்கள்",
    hotlinePurchaseHistory: "ஹாட்லைன் கொள்முதல் வரலாறு",
    connectedBuyerActions: "இணைக்கப்பட்ட வாங்குபவர் நடவடிக்கைகள்",
    supplierCatalogChanges: "தயாரிப்பு பட்டியல் மாற்றங்கள்",
    catalogOrders: "தயாரிப்பு பட்டியல் ஆர்டர்கள்",
    hotRestockSug: "தேவையான இருப்பு பரிந்துரை",
    systemPref: "கணினி விருப்பங்கள்",
    systemPrefDesc: "குரல் விருப்பங்கள், உள்ளீட்டு அமைப்புகள், தீம் முறைகள் மற்றும் அறிவிப்புகளைக் கட்டுப்படுத்தவும்.",
    speechLanguageInterface: "பேச்சு மொழி இடைமுகம்",
    themeMode: "தீம் முறை",
    toggleModeTheme: "தீம் மாற்றவும்",
    voiceOutputEngine: "குரல் வெளியீட்டு இயந்திரம்",
    speechMicInput: "ஒலிவாங்கி உள்ளீடு",
    notificationsCenter: "அறிவிப்பு மையம்",
    notifConnAlerts: "தொடர்பு மாற்றங்களின் எச்சரிக்கைகள்",
    notifStockAlerts: "இருப்பு புதுப்பிப்புகளின் எச்சரிக்கைகள்",

    salesAiAssistant: "விற்பனை AI உதவியாளர்",
    aiBusinessAdvisor: "AI வணிக ஆலோசகர்",
    askSourcingAdvisor: "ஆலோசகரிடம் கேட்கவும்:",
    typeCustomQuestion: "கேள்வியைத் தட்டச்சு செய்க...",
    analyzingSales: "விற்பனையை பகுப்பாய்வு செய்கிறோம்...",
    salesAiWelcome: "வணக்கம்! நான் உங்கள் விற்பனை AI உதவியாளர். நான் உங்கள் தயாரிப்பு பட்டியலை பகுப்பாய்வு செய்ய முடியும், தேவையை கணிக்க முடியும், அல்லது வணிக அறிக்கைகளைத் தயாரிக்க முடியும். தொடங்க கீழே உள்ள கேள்விகளில் ஒன்றைச் தேர்வு செய்யவும்:",

    chipSoldToday: "இன்று எத்தனை பொருட்கள் விற்கப்பட்டன?",
    chipSellsMost: "எந்த தயாரிப்பு அதிகம் விற்கப்படுகிறது?",
    chipRestock: "எந்த தயாரிப்பை நான் மீண்டும் இருப்பு வைக்க வேண்டும்?",
    chipDecreasing: "விற்பனை ஏன் குறைகிறது?",
    chipPricing: "சிறந்த விலையை பரிந்துரைக்கவும்.",
    chipTrends: "வாடிக்கையாளர் கொள்முதல் போக்குகளைக் காட்டு.",
    chipInventory: "இருப்பு மேம்பாடுகளை பரிந்துரைக்கவும்.",
    chipWeekly: "வாராந்திர சுருக்க அறிக்கையை உருவாக்கவும்.",
    chipMonthly: "மாதாந்திர அறிக்கையை உருவாக்கவும்.",
    chipDemand: "தேவையை கணிக்கவும்.",
    chipBestSelling: "அதிகம் விற்கும் தயாரிப்புகளை பரிந்துரைக்கவும்.",

    replySoldToday: "இன்றைய பதிவுகளின்படி, வர்மா உணவுத் தொழிலகம் ₹18,000 மதிப்புள்ள 150 கிலோ பிரீமியம் மஞ்சள் தூளை வாங்கியுள்ளது. உங்கள் ஆர்டர் வெற்றிகரமாக முடிந்தது.",
    replySellsMost: "உங்கள் தயாரிப்பு பட்டியலில் மஞ்சள் தூள் சிறந்த செயல்திறனைப் பெற்றுள்ளது. இந்த மாதத்தில் 720 வாங்குபவர்கள் இதைத் தேர்ந்தெடுத்துள்ளனர்.",
    replyRestock: "சந்தை தேவையின் அடிப்படையில் மஞ்சள் தூள் அதிக தேவையில் உள்ளது. இந்த வாரம் தேடல்கள் 22% அதிகரித்துள்ளன. இருப்பு அளவைப் பராமரிக்க மேலும் 2,000 கிலோ சேர்க்க பரிந்துரைக்கிறோம்.",
    replyDecreasing: "பிராந்திய பாஸ்மதி அரிசி விற்பனை அதிகரித்த போதிலும், மழையின் காரணமாக வరంగல் மற்றும் சென்னை மண்டலங்களில் சிமெண்ட் மற்றும் இரும்பு கம்பிகளின் தேவை 4% குறைந்துள்ளது. மஞ்சள் மற்றும் அரிசி விற்பனை சீராக உள்ளது.",
    replyPricing: "பிராந்திய தேவை அதிகரித்துள்ளதால், பிரீமியம் மஞ்சள் தூள் விலையை ₹120லிருந்து ₹125 ஆக உயர்த்த பரிந்துரைக்கிறோம். இது உங்கள் வாராந்திர லாபத்தை ₹1,500 அதிகரிக்கும்.",
    replyTrends: "மொத்த வியாபாரிகள் பெரிய ஆர்டர்களை வழங்குவதற்கு முன்பு தரத்தை சரிபார்க்க முதலில் சிறிய மாதிரி அளவுகளை (50 முதல் 200 கிலோ வரை) வாங்க விரும்புகிறார்கள்.",
    replyInventory: "இருப்பு பரிந்துரைகள்:\n1. தரமான சான்றிதழ் பெற தேக்கு மரத்தின் தரத்தை மேம்படுத்தவும்.\n2. டெலிவரி தாமதங்களைத் தவிர்க்க பேக்கேஜிங் அட்டைப்பெட்டிகளை எப்போதும் 5,000க்கும் அதிகமாக இருப்பு வைக்கவும்.",
    replyWeekly: "வாராந்திர செயல்திறன் அறிக்கை (05 ஜூலை 2026):\n• செயலில் உள்ள தயாரிப்புகள்: 2\n• இணைக்கப்பட்ட வாங்குபவர்கள்: 128\n• மொத்த வருவாய்: ₹1.85 லட்சம்\n• ஆர்டர் வளர்ச்சி: +12%\n• நம்பகத்தன்மை மதிப்பீடு: 4.8★",
    replyMonthly: "மாதாந்திர சோர்சிங் அறிக்கை:\n• தேடல்களின் எண்ணிக்கை: 1,420\n• வெற்றிகரமான இணைப்புகள்: 128\n• சிறந்த வகைகள்: மஞ்சள், சோனா மசூரி அரிசி\n• மாதாந்திர வளர்ச்சி விகிதம்: +14.5% MoM",
    replyDemand: "தேவை கணிப்பு (அடுத்த 30 நாட்கள்):\n• மஞ்சள் சோர்சிங்: மிக அதிகம் (+18% கணிக்கப்பட்டுள்ளது)\n• அரிசி சோர்சிங்: சீரானது (+6% கணிக்கப்பட்டுள்ளது)\n• சிமெண்ட்/இரும்பு: மிதமான வளர்ச்சி (+4% ஹைதராபாத்தில்)",
    replyBestSelling: "தென்னிந்தியாவில் அதிகம் விற்கப்படும் பொருட்களில் ஈரோடு இயற்கை மஞ்சள் தூள், நெல்லூர் சோனா மசூரி அரிசி மற்றும் நிலநடுக்கத்தை தாங்கும் TMT இரும்பு கம்பிகள் அடங்கும்.",
    replyGeneric: "வணக்கம்! உங்கள் கேள்வியை பகுப்பாய்வு செய்தேன். உங்கள் தயாரிப்புகளின் அடிப்படையில், புதிய ஆர்டர்களைப் பெற இருப்புகளை எப்போதும் தயாராக வைத்திருப்பது முக்கியம். மேலும் விவரங்களுக்கு கேட்கவும்!",
    aiBusinessInsights: "AI வணிக நுண்ணறிவு",
    highDemandTitle: "🔥 அதிக கொள்முதல் தேவை",
    highDemandDesc: "இந்த வாரம் {Product} பல வாங்குபவர்களின் தேடல்களைப் பெற்றுள்ளது. இருப்பு அளவை அதிகரிக்க பரிசீலிக்கவும்.",
    lowStockTitle: "📦 குறைந்த இருப்பு எச்சரிக்கை",
    lowStockDesc: "{Product} இருப்பு குறைவாக உள்ளது. வாங்குபவர்களின் பொருத்தங்களை தொடர்ந்து பெற விரைவில் இருப்பை நிரப்பவும்.",
    pricingTitle: "💰 விலை பரிந்துரை",
    pricingDesc: "இதே போன்ற சப்ளையர்களுடன் ஒப்பிடும்போது உங்கள் {Product} விலை சற்று அதிகமாக உள்ளது. ஒரு {Unit}-க்கு ₹5 குறைப்பது வாங்குபவர்களின் ஆர்வத்தை மேம்படுத்தும்.",
    bestSellingTitle: "⭐ சிறந்த விற்பனை தயாரிப்பு",
    bestSellingDesc: "{Product} இந்த மாதத்தில் அதிக வருவாயை ஈட்டியுள்ளது. இந்த தயாரிப்பை விளம்பரப்படுத்த பரிசீலிக்கவும்.",
    demandForecastTitle: "📈 தேவை கணிப்பு",
    demandForecastDesc: "சமீபத்திய தேடல்களின் அடிப்படையில் அடுத்த வாரம் {Product} தேவை அதிகரிக்கும் என எதிர்பார்க்கப்படுகிறது.",
    regionalTrendTitle: "📍 பிராந்திய போக்கு",
    regionalTrendDesc: "கட்டுமான பொருட்கள் தற்போது ஹைதராபாத்தில் மிக வேகமாக வளர்ந்து வரும் பிரிவாக உள்ளது."
  },
  Kannada: {
    buyerDashboard: "ಖರೀದಿದಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    sellerDashboard: "ಮಾರಾಟಗಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    userDashboard: "ಬಳಕೆದಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    home: "ಮುಖಪುಟ",
    profile: "ಪ್ರೊಫೈಲ್",
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    buyerAccount: "ಖರೀದಿದಾರರ ಖಾತೆ",
    langChangedToast: "ಭಾಷೆಯನ್ನು ಕನ್ನಡಕ್ಕೆ ಬದಲಾಯಿಸಲಾಗಿದೆ.",
    allRead: "ಎಲ್ಲವನ್ನೂ ಓದಿದಂತೆ ಗುರುತಿಸಿ",
    notifCenter: "ಅಧಿಸೂಚನೆ ಕೇಂದ್ರ",
    logout: "ಲಾಗ್ ಔಟ್",

    heroHeading: "ಸಪ್ಲೈ ಮಾರ್ಕೆಟ್",
    heroSubtitle: "AI ಸರಬರಾಜುದಾರರ ಮ್ಯಾಚ್ & ಕಾಲ್ ಕನೆಕ್ಟ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್",
    heroDesc: "ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆಯನ್ನು ಬಳಸಿಕೊಂಡು ಖರೀದಿದಾರರು ವಿಶ್ವಾಸಾರ್ಹ ಸರಬರಾಜುದಾರರನ್ನು ತ್ವರಿತವಾಗಿ ಹುಡುಕಲು ಸಪ್ಲೈ ಮಾರ್ಕೆಟ್ ಸಹಾಯ ಮಾಡುತ್ತದೆ. AI ನಿಮ್ಮ ಅವಶ್ಯಕತೆಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುತ್ತದೆ, ಉತ್ತಮ ಸರಬರಾಜುದಾರರನ್ನು ಹುಡುಕುತ್ತದೆ ಮತ್ತು ವೇಗವಾಗಿ ಸಂಪರ್ಕಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
    goToBuyer: "ಖರೀದಿದಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ",
    goToSeller: "ಮಾರಾಟಗಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ",
    howItWorks: "ಸಪ್ಲೈ ಮಾರ್ಕೆಟ್ ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ",
    howDesc: "ನಿಮ್ಮ ಅವಶ್ಯಕತೆಗಳನ್ನು ಸುರಕ್ಷಿತ ನೇರ ಕರೆಗಳಾಗಿ ಪರಿವರ್ತಿಸುವ ನಾಲ್ಕು ಸುಲಭ ಹಂತಗಳು.",
    whyChoose: "ಸಪ್ಲೈ ಮಾರ್ಕೆಟ್ ಅನ್ನು ಏಕೆ ಆರಿಸಬೇಕು",
    whyDesc: "ವ್ಯವಹಾರಗಳ ನಡುವೆ ನಂಬಿಕೆಯನ್ನು ಬೆಳೆಸಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ಪ್ರೀಮಿಯಂ, ಸರಳ ವ್ಯಾಪಾರ ವೇದಿಕೆ.",
    step1Title: "ಅವಶ್ಯಕತೆ ವಿವರಿಸಿ",
    step1Desc: "ನಿಮ್ಮ ಪ್ರಮಾಣ, ಗುಣಮಟ್ಟ ಮತ್ತು ಸ್ಥಳವನ್ನು ಪಠ್ಯ ಅಥವಾ ಧ್ವನಿ ಮೂಲಕ ವಿವರಿಸಿ.",
    step2Title: "AI ಉತ್ತಮ ಸರಬರಾಜುದಾರರನ್ನು ಹುಡುಕುತ್ತದೆ",
    step2Desc: "ನಮ್ಮ ಮ್ಯಾಚಿಂಗ್ ಎಂಜಿನ್ ವಿವರಗಳನ್ನು ಹುಡುಕುತ್ತದೆ ಮತ್ತು ಹೆಚ್ಚು ಸೂಕ್ತವಾದ ಸರಬರಾಜುದಾರರನ್ನು ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ.",
    step3Title: "ಸರಬರಾಜುದಾರರ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ",
    step3Desc: "ರೂಪಾಯಿಗಳಲ್ಲಿ ಬೆಲೆಗಳು, ಸ್ಟಾಕ್ ಪ್ರಮಾಣ, ಸ್ಥಳ ಮತ್ತು ರೇಟಿಂಗ್‌ಗಳನ್ನು ಹೋಲಿಕೆ ಮಾಡಿ.",
    step4Title: "ನೇರ ಸಂಪರ್ಕಿಸಿ",
    step4Desc: "ಚರ್ಚೆಯನ್ನು ಪ್ರಾರಂಭಿಸಲು ಸುರಕ್ಷಿತ ಟೆಲಿಫೋನ್ ಡಯಲರ್ ಸಂಪರ್ಕಗಳನ್ನು ಬಳಸಿ.",
    feat1Title: "ವೇಗದ ಸರಬರಾಜುದಾರರ ಹುಡುಕಾಟ",
    feat1Desc: "ಸರಿಯಾದ ಸರಬರಾಜುದಾರರನ್ನು ತಕ್ಷಣವೇ ಹುಡುಕಿ. ಹಸ್ತಚಾಲಿತ ಕರೆಗಳನ್ನು ಮಾಡುವ ಸಮಯವನ್ನು ಉಳಿಸಿ.",
    feat2Title: "ವಿಶ್ವಾಸಾರ್ಹ ವ್ಯವಹಾರಗಳು",
    feat2Desc: "ಉತ್ತಮ ನಂಬಿಕೆ ಸ್ಕೋರುಗಳು ಮತ್ತು ಉತ್ತಮ ಕಾರ್ಯಕ್ಷಮತೆಯ ಆಧಾರಗಳಿರುವ ಧೃಡೀಕೃತ ಸಂಸ್ಥೆಗಳೊಂದಿಗೆ ಮಾತ್ರ ಸಂಪರ್ಕಿಸಿ.",
    feat3Title: "AI ಧ್ವನಿ ಸಹಾಯಕ",
    feat3Desc: "ಸಂಭಾಷಣಾ ಧ್ವನಿ ಸಹಾಯಕ ಮ್ಯಾಚಿಂಗ್ ವಿವರಗಳನ್ನು ಸುಲಭವಾಗಿ ಕೇಳುವಂತೆ ಮಾಡುತ್ತದೆ.",
    feat4Title: "ಹಲವು ಭಾಷೆಗಳು",
    feat4Desc: "ಕನ್ನಡ, ತೆಲುಗು, ಹಿಂದಿ, ತಮಿಳು, ಮಲಯಾಳಂ ಮತ್ತು ಇಂಗ್ಲಿಷ್: 6 ಭಾರತೀಯ ಭಾಷೆಗಳಲ್ಲಿ ಮಾತನಾಡಿ ಮತ್ತು ಸೂಚನೆಗಳನ್ನು ಪಡೆಯಿರಿ.",
    feat5Title: "ಸ್ಮಾರ್ಟ್ ಶಿಫಾರಸುಗಳು",
    feat5Desc: "ಪ್ರತಿಯೊಂದು ಆಯ್ಕೆಯು ನಿಮಗೆ ಏಕೆ ಹೆಚ್ಚು ಸೂಕ್ತವಾಗಿದೆ ಎಂಬುದಕ್ಕೆ AI ಸ್ಪಷ್ಟ ಕಾರಣಗಳನ್ನು ನೀಡುತ್ತದೆ.",
    feat6Title: "ವ್ಯವಹಾರ ಸಂಪರ್ಕಗಳು",
    feat6Desc: "ಸಂಪರ್ಕಗಳನ್ನು ಉಳಿಸಿ ಮತ್ತು ಮತ್ತೆ ವ್ಯಾಪಾರ ಮಾಡಲು ಕಂಪನಿಯ ಡೈರೆಕ್ಟರಿಗಳನ್ನು ಫಾಲೋ ಮಾಡಿ.",

    findRightSupplier: "ಸರಿಯಾದ ಸರಬರಾಜುದಾರರನ್ನು ಹುಡುಕಿ",
    tellUsNeed: "ನಿಮಗೆ ಏನು ಬೇಕು ಎಂದು ನಮಗೆ ತಿಳಿಸಿ. ಉತ್ತಮ ಸರಬರಾಜುದಾರರನ್ನು ಹುಡುಕಲು ನಮ್ಮ AI ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
    searchPlaceholder: 'ಉದಾಹರಣೆ: "ನನ್ನ ಗಿಡಮೂಲಿಕೆ ಉತ್ಪನ್ನಗಳ ವ್ಯವಹಾರಕ್ಕಾಗಿ ನನಗೆ 100 ಕೆಜಿ ಪ್ರೀಮಿಯಂ ಅರಿಶಿನ ಬೇಕು."',
    speakBtn: "ಮಾತನಾಡಿ",
    findSuppliersBtn: "ಸರಬರಾಜುದಾರರನ್ನು ಹುಡುಕಿ",
    clearBtn: "ಕ್ಲಿಯರ್",
    listeningLabel: "ಕೇಳುತ್ತಿದ್ದೇವೆ. ನಿಮ್ಮ ಅವಶ್ಯಕತೆಯನ್ನ ಮಾತನಾಡಿ...",
    matchingSuppliers: "ಸರಬರಾಜುದಾರರನ್ನು ಹೋಲಿಸುತ್ತಿದ್ದೇವೆ...",
    popularSearches: "ಜನಪ್ರಿಯ ಶೋಧನೆಗಳು:",
    processingHeuristics: "ಮ್ಯಾಚಿಂಗ್ ವಿಧಾನಗಳನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತಿದ್ದೇವೆ",
    processingDesc: "ಇನ್ವೆಂಟರಿ ಡೇಟಾಬೇಸ್ ಮತ್ತು ವಿತರಣಾ ಮಾರ್ಗಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತಿದ್ದೇವೆ.",
    aiRecomHeading: "AI ಶಿಫಾರಸು ಆಯ್ಕೆ",
    bestMatch: "ಉತ್ತಮ ಆಯ್ಕೆ",
    ratingLabel: "ರೇಟಿಂಗ್",
    locationLabel: "ಸ್ಥಳ",
    availToday: "ಇಂದು ಲಭ್ಯವಿದೆ",
    matchScore: "ಮ್ಯಾಚ್ ಸ್ಕೋರು",
    reasonForRecom: "ಶಿಫಾರಸು ಮಾಡಲು कारण:",
    productOfferPrice: "ಉತ್ಪನ್ನದ ಬೆಲೆ",
    connectBtn: "ಕನೆಕ್ಟ್",
    viewDetailsBtn: "ವಿವರಗಳನ್ನು ನೋಡಿ",
    saveBtn: "ಉಳಿಸಿ",
    savedBtn: "ಉಳಿಸಲಾಗಿದೆ",
    aiSummaryHeading: "AI ಸೋರ್ಸಿಂಗ್ ಸಾರಾಂಶ",
    reqLabel: "ನಿಮ್ಮ ಅವಶ್ಯಕತೆ",
    selSupplierLabel: "ಆಯ್ಕೆ ಮಾಡಿದ ಸರಬರಾಜುದಾರರು",
    priceLabel: "ಬೆಲೆ",
    qtyLabel: "ಪ್ರಮಾಣ",
    reasonSelLabel: "ಆಯ್ಕೆಗೆ ಕಾರಣ",
    nextStepLabel: "ಮುಂದಿನ ಹಂತದ ಶಿಫಾರಸು",
    otherOptions: "ಇತರ ಸೋೋರ್ಸ್ ಮಾಡಿದ ಆಯ್ಕೆಗಳು",
    browseSuppliersManually: "ಸರಬರಾಜುದಾರರನ್ನು ನೇರವಾಗಿ ಹುಡುಕಿ",
    browseDesc: "ಧೃಡೀಕೃತ ಸರಬರಾಜುದಾರರ ಡೇಟಾಬೇಸ್ ಮೂಲಕ ವೆತಕಿ ಮತ್ತು ಫಿಲ್ಟರ್ ಮಾಡಿ.",
    productSearchLabel: "ಉತ್ಪನ್ನ ಹುಡುಕಾಟ",
    locationCityLabel: "ನಗರ / ಸ್ಥಳ",
    productCatLabel: "ಉತ್ಪನ್ನದ ವರ್ಗ",
    allCategories: "ಎಲ್ಲಾ ವರ್ಗಗಳು",
    minPriceLabel: "ಕನಿಷ್ಠ ಬೆಲೆ (₹)",
    maxPriceLabel: "ಗರಿಷ್ಠ ಬೆಲೆ (₹)",
    minRatingLabel: "ಕನಿಷ್ಠ ರೇಟಿಂಗ್",
    allRatings: "ಎಲ್ಲಾ ರೇಟಿಂಗ್‌ಗಳು",
    availTodayFilter: "ಇಂದು ಲಭ್ಯವಿದೆ",
    viewBtn: "ನೋಡಿ",
    followBtn: "ಫಾಲೋ",
    followingBtn: "ಫಾಲೋ ಮಾಡುತ್ತಿದ್ದೀರಿ",
    noSellersFound: "ಹಸ್ತಚಾಲಿತ ಡೈರೆಕ್ಟರಿ ಹುಡುಕಾಟದಲ್ಲಿ ಯಾವುದೇ ಹೊಂದಾಣಿಕೆಯ ಸರಬರಾಜುದಾರರು ಕಂಡುಬಂದಿಲ್ಲ.",

    aiSpeaking: "AI ಮಾತನಾಡುತ್ತಿದೆ",
    connectSupplier: "ಸರಬರಾಜುದಾರರನ್ನು ಸಂಪರ್ಕಿಸಿ",
    askAi: "AI ಗೆ ಕೇಳಿ",
    findMore: "ಇನ್ನಷ್ಟು ಹುಡುಕಿ",

    step1: "ನಿಮ್ಮ ಅವಶ್ಯಕತೆಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುತ್ತಿದ್ದೇವೆ",
    step2: "ಸರಬರಾಜುದಾರರನ್ನು ಹುಡುಕುತ್ತಿದ್ದೇವೆ",
    step3: "ಬೆಲೆಗಳನ್ನು ಹೋಲಿಸುತ್ತಿದ್ದೇವೆ",
    step4: "ಸ್ಟಾಕ್ ಪರಿಶೀಲಿಸುತ್ತಿದ್ದೇವೆ",
    step5: "ಉತ್ತಮ ಸರಬರಾಜುದಾರರನ್ನು ಆಯ್ಕೆ ಮಾಡುತ್ತಿದ್ದೇವೆ",
    step6: "ಉತ್ತರವನ್ನು ಸಿದ್ಧಪಡಿಸುತ್ತಿದ್ದೇವೆ",

    connecting: "ಸಂಪರ್ಕಿಸುತ್ತಿದ್ದೇವೆ...",
    connectingDesc: "ಸುರಕ್ಷಿತ ಕರೆ ಲೈನ್‌ಗಳನ್ನು ಸ್ಥಾಪಿಸುತ್ತಿದ್ದೇವೆ ಮತ್ತು ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ಸಿಂಕ್ ಮಾಡುತ್ತಿದ್ದೇವೆ.",
    connSuccessful: "ಸಂಪರ್ಕ ಯಶಸ್ವಿಯಾಗಿದೆ",
    yourIdentity: "ನಿಮ್ಮ ಗುರುತು",
    supplierSourced: "ಸೋರ್ಸ್ ಮಾಡಿದ ಸಪ್ಲಯರ್",
    connConnected: "ಸಂಪರ್ಕಗೊಂಡಿದೆ",
    connSuccessText: "ಖರೀದಿದಾರರು ಮತ್ತು ಸರಬರಾಜುದಾರರು ಈಗ ಸಂಪರ್ಕ ಹೊಂದಿದ್ದಾರೆ. ನೀವು ನೇರವಾಗಿ ಮಾತನಾಡಬಹುದು.",
    callSalesBtn: "ಸೇಲ್ಸ್ ಪ್ರತಿನಿಧಿಗೆ ಕರೆ ಮಾಡಿ",
    doneBtn: "ಮುಗಿಯಿತು",

    activeListings: "ಸಕ್ರಿಯ ಕ್ಯಾಟಲಾಗ್ ಪಟ್ಟಿಗಳು",
    activeOrders: "ಸಕ್ರಿಯ ಆರ್ಡರ್ಗಳು",
    connectedBuyers: "ಸಂಪರ್ಕಗೊಂಡ ಖರೀದಿದಾರರು",
    revenueLabel: "ಆದಾಯ",
    salesValue: "ದಾಖಲಾದ ಮಾರಾಟದ ಮೌಲ್ಯ",
    aiSourcingSug: "AI ಸೋರ್ಸಿಂಗ್ ಶಿಫಾರಸುಗಳು",
    inventorySourcingCat: "ಇನ್ವೆಂಟರಿ ಸೋರ್ಸಿಂಗ್ ಕ್ಯಾಟಲಾಗ್",
    inventorySourcingDesc: "ಗ್ರಾಹಕರ ಅಗತ್ಯತೆಗಳಿಗೆ ಹೊಂದುವ ನಿಮ್ಮ ಉತ್ಪನ್ನಗಳ ವಿವರಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
    addProduct: "ಉತ್ಪನ್ನ ಸೇರಿಸಿ",
    editProduct: "ಉತ್ಪನ್ನ ಸಂಪಾದಿಸಿ",
    deleteProduct: "ಉತ್ಪನ್ನ ಅಳಿಸಿ",
    recentConnectedBuyers: "ಇತ್ತೀಚೆಗೆ ಸಂಪರ್ಕಗೊಂಡ ಖರೀದಿದಾರರು",
    recentConnectedDesc: "ಸುರಕ್ಷಿತ AI ಧ್ವನಿ ಮೂಲಕ ಏರ್ಪಟ್ಟ ಸಂಪರ್ಕಗಳು.",
    viewBuyer: "ಖರೀದಿದಾರರ ವಿವರಗಳು",
    contactBuyer: "ಖರೀದಿದಾರರನ್ನು ಸಂಪರ್ಕಿಸಿ",
    saveChanges: "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    availableTodayModal: "ಇಂದು ಲಭ್ಯವಿದೆ (ತಕ್ಷಣ ರವಾನೆ ಸಕ್ರಿಯವಾಗಿದೆ)",
    modalAvailable: "ಲಭ್ಯವಿದೆ",

    prodNameField: "ಉತ್ಪನ್ನದ ಹೆಸರು",
    catField: "ವರ್ಗ",
    priceField: "ಬೆಲೆ",
    qtyField: "ಪ್ರಮಾಣ",
    qualityField: "ಗುಣಮಟ್ಟ",
    locField: "ನಗರ",
    busNameField: "ವ್ಯಾಪಾರದ ಹೆಸರು",
    phoneField: "ಫೋನ್ ಸಂಖ್ಯೆ",
    availabilityField: "ಲಭ್ಯತೆ",
    actionsField: "ಕ್ರಮಗಳು",

    userConsole: "ಬಳಕೆದಾರರ ಕನ್ಸೋಲ್",
    userConsoleDesc: "ನಿಮ್ಮ ವ್ಯವಹಾರ ಸಂಪರ್ಕಗಳು, ಚಟುವಟಿಕೆಯ ಇತಿಹಾಸ ಮತ್ತು ಭಾಷಾ ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
    profileIdentity: "ಪ್ರೊಫೈಲ್ ಗುರುತು",
    hotlineConnections: "ಸಂಪರ್ಕಗಳ ಹಾಟ್‌ಲೈನ್",
    recentActivity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
    consoleSettings: "ಕನ್ಸೋಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    headquarters: "ಪ್ರಧಾನ ಕಛೇರಿ",
    activeCatalogReg: "ಸಕ್ರಿಯ ಕ್ಯಾಟಲಾಗ್ ನೋಂದಣಿ",
    bothBadge: "ಎರಡೂ (ಖರೀದಿದಾರ ಮತ್ತು ಸರಬರಾಜುದಾರ)",
    procurementManager: "ಖರೀದಿ ಮತ್ತು ಸಗಟು ವಿಭಾಗದ ವ್ಯವಸ್ಥಾಪಕರು",
    corporateEmail: "ಕಾರ್ಪೊರೇಟ್ ಇಮೇಲ್",
    mobilePhone: "ಮೊಬೈಲ್ ಫೋನ್",
    connHotlineTitle: "ವ್ಯವಹಾರ ಸಂಪರ್ಕಗಳ ಹಾಟ್‌ಲೈನ್",
    connHotlineDesc: "ವಿಶ್ವಾಸಾರ್ಹ ಸರಬರಾಜುದಾರರಿಗೆ ನೇರವಾಗಿ ಸಂಪರ್ಕಿಸಿ. ಉಳಿಸಿದ ಸಂಪರ್ಕಗಳಿಗಾಗಿ AI ಅಗತ್ಯವಿಲ್ಲ.",
    removeConn: "ತೆಗೆದುಹಾಕಿ",
    sendMessage: "ಸಂದೇಶ ಕಳುಹಿಸಿ",
    buyerActivity: "ಖರೀದಿದಾರರ ಚಟುವಟಿಕೆ",
    sellerActivity: "ಸರಬರಾಜುದಾರರ ಚಟುವಟಿಕೆ",
    recentSearches: "ಇತ್ತೀಚಿನ ಶೋಧನೆಗಳು",
    recentConversationalLogs: "ಇತ್ತೀಚಿನ ಧ್ವನಿ ಸಂಭಾಷಣೆಗಳು",
    savedSourcedSuppliers: "ಉಳಿಸಿದ ಸರಬರಾಜುದಾರರು",
    hotlinePurchaseHistory: "ಹಾಟ್‌ಲೈನ್ ಖರೀದಿ ಇತಿಹಾಸ",
    connectedBuyerActions: "ಸಂಪರ್ಕಗೊಂಡ ಬೈಯರ್ ಕ್ರಮಗಳು",
    supplierCatalogChanges: "ಕ್ಯಾಟಲಾಗ್ ಬದಲಾವಣೆಗಳು",
    catalogOrders: "ಕ್ಯಾಟಲಾಗ್ ಆರ್ಡರ್ಗಳು",
    hotRestockSug: "ಅಗತ್ಯವಿರುವ ಸ್ಟಾಕ್ ಶಿಫಾರಸು",
    systemPref: "ಸಿಸ್ಟಮ್ ಆದ್ಯತೆಗಳು",
    systemPrefDesc: "ಧ್ವನಿ ಆದ್ಯತೆಗಳು, ಇನ್‌ಪುಟ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು, ಥೀಮ್ ಮೋಡ್‌ಗಳು ಮತ್ತು ಅಧಿಸೂಚನೆಗಳನ್ನು ನಿಯಂತ್ರಿಸಿ.",
    speechLanguageInterface: "ಮಾತು ಭಾಷೆ ಇಂಟರ್ಫೇಸ್",
    themeMode: "ಥೀಮ್ ಮೋಡ್",
    toggleModeTheme: "ಥೀಮ್ ಬದಲಾಯಿಸಿ",
    voiceOutputEngine: "ಧ್ವನಿ ಔಟ್‌ಪುಟ್ ಎಂಜಿನ್",
    speechMicInput: "ಮೈಕ್ರೊಫೋನ್ ಇನ್ಪುಟ್",
    notificationsCenter: "ಅಧಿಸೂಚನೆ ಕೇಂದ್ರ",
    notifConnAlerts: "ಸಂಪರ್ಕ ಬದಲಾವಣೆಗಳ ಎಚ್ಚರಿಕೆಗಳು",
    notifStockAlerts: "ಸ್ಟಾಕ್ ನವೀಕರಣಗಳ ಎಚ್ಚರಿಕೆಗಳು",

    salesAiAssistant: "ಸೇಲ್ಸ್ AI ಸಹಾಯಕ",
    aiBusinessAdvisor: "AI ವ್ಯವಹಾರ ಸಲಹೆಗಾರ",
    askSourcingAdvisor: "ಸಲಹೆಗಾರರಿಗೆ ಕೇಳಿ:",
    typeCustomQuestion: "ಪ್ರಶ್ನೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ...",
    analyzingSales: "ನಿಮ್ಮ ಮಾರಾಟವನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತಿದ್ದೇವೆ...",
    salesAiWelcome: "ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ ಸೇಲ್ಸ್ AI ಸಹಾಯಕ. ನಾನು ನಿಮ್ಮ ಕ್ಯಾಟಲಾಗ್ ವಿಶ್ಲೇಷಿಸಬಲ್ಲೆ, ಬೇಡಿಕೆಯನ್ನು ಊಹಿಸಬಲ್ಲೆ, ಅಥವಾ ವ್ಯವಹಾರ ವರದಿಗಳನ್ನು ಸಿದ್ಧಪಡಿಸಬಲ್ಲೆ. ಪ್ರಾರಂಭಿಸಲು ಕೆಳಗಿನ ಪ್ರಶ್ನೆಗಳಲ್ಲಿ ಒಂದನ್ನು ಆರಿಸಿ:",

    chipSoldToday: "ಇಂದು ಎಷ್ಟು ಉತ್ಪನ್ನಗಳು ಮಾರಾಟವಾಗಿವೆ?",
    chipSellsMost: "ಯಾವ ಉತ್ಪನ್ನ ಅತಿ ಹೆಚ್ಚು ಮಾರಾಟವಾಗುತ್ತದೆ?",
    chipRestock: "ನಾನು ಯಾವ ಉತ್ಪನ್ನವನ್ನು ಮತ್ತೆ ಸ್ಟಾಕ್ ಮಾಡಬೇಕು?",
    chipDecreasing: "ಮಾರಾಟ ಏಕೆ ಕಡಿಮೆಯಾಗುತ್ತಿದೆ?",
    chipPricing: "ಉತ್ತಮ ಬೆಲೆಯನ್ನು ಸೂಚಿಸಿ.",
    chipTrends: "ಗ್ರಾಹಕ ಖರೀದಿ ಪ್ರವೃತ್ತಿಗಳನ್ನು ತೋರಿಸಿ.",
    chipInventory: "ದಾಸ್ತಾನು ಸುಧಾರಣೆಗಳನ್ನು ಶಿಫಾರಸು ಮಾಡಿ.",
    chipWeekly: "ವಾರದ ವರದಿಯನ್ನು ತಯಾರಿಸಿ.",
    chipMonthly: "ತಿಂಗಳ ವರದಿಯನ್ನು ತಯಾರಿಸಿ.",
    chipDemand: "ಬೇಡಿಕೆಯನ್ನು ಅಂದಾಜು ಮಾಡಿ.",
    chipBestSelling: "ಅತಿ ಹೆಚ್ಚು ಮಾರಾಟವಾಗುವ ಉತ್ಪನ್ನಗಳನ್ನು ಸೂಚಿಸಿ.",

    replySoldToday: "ಇಂದಿನ ದಾಖಲೆಗಳ ಪ್ರಕಾರ, ವರ್ಮಾ ಫುಡ್ ಇಂಡಸ್ಟ್ರೀಸ್ ₹18,000 ಮೌಲ್ಯದ 150 ಕೆಜಿ ಪ್ರೀಮಿಯಂ ಅರಿಶಿನ ಪುಡಿಯನ್ನು ಖರೀದಿಸಿದೆ. ನಿಮ್ಮ ಆರ್ಡರ್ ಪೂರ್ಣಗೊಂಡಿದೆ.",
    replySellsMost: "ನಿಮ್ಮ ಕ್ಯಾಟಲಾಗ್‌ನಲ್ಲಿ ಅತ್ಯುತ್ತಮ ಮಾರಾಟ ಕಾಣುತ್ತಿರುವುದು ಅರಿಶಿನ ಪುಡಿ. ಈ ತಿಂಗಳು 720 ಖರೀದಿದಾರರ ಮ್ಯಾಚ್‌ಗಳೊಂದಿಗೆ ಇದು ಮೊದಲ ಸ್ಥಾನದಲ್ಲಿದೆ.",
    replyRestock: "ಮಾರುಕಟ್ಟೆ ಬೇಡಿಕೆಯ ವಿಶ್ಲೇಷಣೆಯ ಪ್ರಕಾರ ಅರಿಶಿನ ಪುಡಿಗೆ ಭಾರಿ ಬೇಡಿಕೆಯಿದೆ. ಈ ವಾರ ಹುಡುಕಾಟಗಳು 22% ಹೆಚ್ಚಾಗಿವೆ. ಬಫರ್ ಸ್ಟಾಕ್ ಕಾಯ್ದುಕೊಳ್ಳಲು 2,000 ಕೆಜಿ ಸೇರಿಸಲು ಶಿಫಾರಸು ಮಾಡುತ್ತೇವೆ.",
    replyDecreasing: "ಪ್ರಾದೇಶಿಕ ಬಾಸುಮತಿ ಅಕ್ಕಿ ಮಾರಾಟ ಹೆಚ್ಚಿದರೂ, ಮಳೆಯ ಕಾರಣ ವಾರಂಗಲ್ ಮತ್ತು ಚೆನ್ನೈ ವಲಯಗಳಲ್ಲಿ ಸಿಮೆಂಟ್ ಮತ್ತು ಕಬ್ಬಿಣದ ಬೇಡಿಕೆ 4% ಕಡಿಮೆಯಾಗಿದೆ. ಅರಿಶಿನ ಮತ್ತು ಅಕ್ಕಿ ಮಾರಾಟ ಸ್ಥಿರವಾಗಿದೆ.",
    replyPricing: "ಪ್ರಾದೇಶಿಕ ಬೇಡಿಕೆ ಹೆಚ್ಚಿರುವುದರಿಂದ, ನಾವು ಅರಿಶಿನ ಪುಡಿ ಬೆಲೆಯನ್ನು ₹120 ರಿಂದ ₹125 ಕ್ಕೆ ಹೆಚ್ಚಿಸಲು ಸೂಚಿಸುತ್ತೇವೆ. ಇದು ನಿಮ್ಮ ವಾರದ ಲಾಭವನ್ನು ₹1,500 ಹೆಚ್ಚಿಸುತ್ತದೆ.",
    replyTrends: "ಸಗಟು ವ್ಯಾಪಾರಿಗಳು ದೊಡ್ಡ ಆರ್ಡರ್ ನೀಡುವ ಮುನ್ನ ಗುಣಮಟ್ಟ ಪರೀಕ್ಷಿಸಲು ಮೊದಲು ಸಣ್ಣ ಸ್ಯಾಂಪಲ್ ಗಾತ್ರಗಳನ್ನು (50 ರಿಂದ 200 ಕೆಜಿ) ಖರೀದಿಸಲು ಇಷ್ಟಪಡುತ್ತಾರೆ.",
    replyInventory: "ದಾಸ್ತಾನು ಶಿಫಾರಸುಗಳು:\n1. ಗ್ರೇಡ್-ಎ ಪ್ರಮಾಣೀಕರಣ ಪಡೆಯಲು ತೇಗದ ಮರದ ಗುಣಮಟ್ಟದ ಮಾನದಂಡಗಳನ್ನು ಸುಧಾರಿಸಿ.\n2. ಡೆಲಿವರಿ ವಿಳಂಬ ತಪ್ಪಿಸಲು ಪ್ಯಾಕೇಜಿಂಗ್ ಕಾರ್ಟನ್‌ಗಳನ್ನು ಕನಿಷ್ಠ 5,000 ಸ್ಟಾಕ್‌ನಲ್ಲಿ ಕಾಯ್ದುಕೊಳ್ಳಿ.",
    replyWeekly: "ವಾರದ ಕಾರ್ಯಕ್ಷಮತೆಯ ವರದಿ (05 ಜುಲೈ 2026):\n• ಸಕ್ರಿಯ ಪಟ್ಟಿಗಳು: 2 ಉತ್ಪನ್ನಗಳು\n• ಸಂಪರ್ಕಿತ ಖರೀದಿದಾರರು: 128\n• ಒಟ್ಟು ಆದಾಯ: ₹1.85 ಲಕ್ಷಗಳು\n• ಆರ್ಡರ್ ವೃದ್ಧಿ: +12% ಹೆಚ್ಚಳ\n• ನಂಬಿಕೆ ರೇಟಿಂಗ್: 4.8★",
    replyMonthly: "ಮಾಸಿಕ ಸೋರ್ಸಿಂಗ್ ವರದಿ:\n• ಹುಡುಕಾಟಗಳ ಸಂಖ್ಯೆ: 1,420 ಹಿಟ್ಸ್\n• ಯಶಸ್ವಿ ಸಂಪರ್ಕಗಳು: 128\n• ಪ್ರಮುಖ ವರ್ಗಗಳು: ಅರಿಶಿನ, ಸೋನಾ ಮಸೂರಿ ಅಕ್ಕಿ\n• ಮಾಸಿಕ ಬೆಳವಣಿಗೆ ದರ: +14.5% MoM",
    replyDemand: "ಬೇಡಿಕೆಯ ಮುನ್ಸೂಚನೆ (ಮುಂದಿನ 30 ದಿನಗಳು):\n• ಅರಿಶಿನ ಸೋರ್ಸಿಂಗ್: ಅತ್ಯಂತ ಹೆಚ್ಚು (+18% ಅಂದಾಜಿಸಲಾಗಿದೆ)\n• ಅಕ್ಕಿ ಸೋರ್ಸಿಂಗ್: ಸ್ಥಿರವಾಗಿದೆ (+6% ಅಂದಾಜಿಸಲಾಗಿದೆ)\n• ಸಿಮೆಂಟ್/ಕಬ್ಬಿಣ: ಸಾಧಾರಣ ಬೆಳವಣಿಗೆ (+4% ಹೈದರಾಬಾದ್‌ನಲ್ಲಿ)",
    replyBestSelling: "ದಕ್ಷಿಣ ಭಾರತದಲ್ಲಿ ಅತಿ ಹೆಚ್ಚು ಮಾರಾಟವಾಗುವ ಉತ್ಪನ್ನಗಳಲ್ಲಿ ಈರೋಡ್ ಸಾವಯವ ಅರಿಶಿನ ಪುಡಿ, ನೆಲ್ಲೂರು ಸೋನಾ ಮಸೂರಿ ಅಕ್ಕಿ ಮತ್ತು ಭೂಕಂಪ ನಿರೋಧಕ TMT ಕಬ್ಬಿಣದ ಸರಳುಗಳು ಸೇರಿವೆ.",
    replyGeneric: "ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ವಿಶ್ಲೇಷಿಸಿದ್ದೇನೆ. ನಿಮ್ಮ ಕ್ಯಾಟಲಾಗ್ ಉತ್ಪನ್ನಗಳ ಆಧಾರದ ಮೇಲೆ, ಆರ್ಡರ್ ಪಡೆಯಲು ಸ್ಟಾಕ್ ತಕ್ಷಣ ಸಿದ್ಧವಾಗಿಟ್ಟುಕೊಳ್ಳುವುದು ಮುಖ್ಯ. ಹೆಚ್ಚಿನ ವಿವರಗಳಿಗಾಗಿ ಕೇಳಿ!",
    aiBusinessInsights: "AI ವ್ಯವಹಾರ ಒಳನೋಟಗಳು",
    highDemandTitle: "🔥 ಹೆಚ್ಚಿನ ಗ್ರಾಹಕ ಬೇಡಿಕೆ",
    highDemandDesc: "{Product} ಈ ವಾರ ಅನೇಕ ಗ್ರಾಹಕರ ಹುಡುಕಾಟಗಳನ್ನು ಪಡೆದಿದೆ. ಲಭ್ಯವಿರುವ ಸ್ಟಾಕ್ ಹೆಚ್ಚಿಸಲು ಪರಿಗಣಿಸಿ.",
    lowStockTitle: "📦 ಕಡಿಮೆ ಸ್ಟಾಕ್ ಎಚ್ಚರಿಕೆ",
    lowStockDesc: "{Product} ದಾಸ್ತಾನು ಮುಗಿಯುತ್ತಾ ಬಂದಿದೆ. ಗ್ರಾಹಕರ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ಪಡೆಯುವುದನ್ನು ಮುಂದುವರಿಸಲು ಶೀಘ್ರದಲ್ಲೇ ಮರುಸ್ಥಾಪಿಸಿ.",
    pricingTitle: "💰 ಬೆಲೆ ಶಿಫಾರಸು",
    pricingDesc: "ಇತರ ಸರಬರಾಜುದಾರರಿಗೆ ಹೋലಿಸಿದರೆ ನಿಮ್ಮ {Product} ಬೆಲೆ ಸ್ವಲ್ಪ ಹೆಚ್ಚಾಗಿದೆ. ಬೆಲೆಯನ್ನು ಪ್ರತಿ {Unit} ಗೆ ₹5 ರಷ್ಟು ಕಡಿಮೆ ಮಾಡುವುದರಿಂದ ಆಸಕ್ತಿ ಹೆಚ್ಚಬಹುದು.",
    bestSellingTitle: "⭐ ಹೆಚ್ಚು ಮಾರಾಟವಾಗುವ ಉತ್ಪನ್ನ",
    bestSellingDesc: "{Product} ಈ ತಿಂಗಳು ಅತಿ ಹೆಚ್ಚು ಆದಾಯವನ್ನು ತಂದಿದೆ. ಈ ಉತ್ಪನ್ನವನ್ನು ಪ್ರಚಾರ ಮಾಡಲು ಪರಿಗಣಿಸಿ.",
    demandForecastTitle: "📈 ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆ",
    demandForecastDesc: "ಇತ್ತೀಚಿನ ಹುಡುಕಾಟಗಳ ಆಧಾರದ ಮೇಲೆ ಮುಂದಿನ ವಾರ {Product} ಬೇಡಿಕೆ ಹೆಚ್ಚಾಗುವ ನಿರೀಕ್ಷೆಯಿದೆ.",
    regionalTrendTitle: "📍 ಪ್ರಾದೇಶಿಕ ಪ್ರವೃತ್ತಿ",
    regionalTrendDesc: "ಪ್ರಸ್ತುತ ಹೈദರಾಬಾದ್‌ನಲ್ಲಿ ನಿರ್ಮಾಣ ಸಾಮಗ್ರಿಗಳು ಅತ್ಯಂತ ವೇಗವಾಗಿ ಬೆಳೆಯುತ್ತಿರುವ ವಿಭಾಗವಾಗಿದೆ."
  },
  Malayalam: {
    buyerDashboard: "ബയർ ഡാഷ്‌ബോർഡ്",
    sellerDashboard: "സെല്ലർ ഡാഷ്‌ബോർഡ്",
    userDashboard: "യൂസർ ഡാഷ്‌ബോർഡ്",
    home: "ഹോം",
    profile: "പ്രൊഫൈൽ",
    notifications: "അറിയിപ്പുകൾ",
    buyerAccount: "വാങ്ങുന്നയാളുടെ അക്കൗണ്ട്",
    langChangedToast: "ഭാഷ മലയാളത്തിലേക്ക് മാറ്റി.",
    allRead: "എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക",
    notifCenter: "അറിയിപ്പ് കേന്ദ്രം",
    logout: "ലോഗ് ഔട്ട്",

    heroHeading: "സപ്ലൈ മാർക്കറ്റ്",
    heroSubtitle: "AI സപ്ലയർ മാച്ച് & കോൾ കണക്ട് പ്ലാറ്റ്ഫോം",
    heroDesc: "കൃത്രിമ ബുദ്ധി ഉപയോഗിച്ച് വാങ്ങുന്നവർക്ക് വിശ്വസനീയമായ വിതരണക്കാരെ വേഗത്തിൽ കണ്ടെത്താൻ സപ്ലൈ മാർക്കറ്റ് സഹായിക്കുന്നു. AI നിങ്ങളുടെ ആവശ്യകത മനസ്സിലാക്കുകയും ഏറ്റവും അനുയോജ്യനായ വിതരണക്കാരനെ കണ്ടെത്തുകയും വേഗത്തിൽ ബന്ധിപ്പിക്കാൻ സഹായിക്കുകയും ചെയ്യുന്നു.",
    goToBuyer: "ബയർ ഡാഷ്‌ബോർഡിലേക്ക് പോകുക",
    goToSeller: "സെല്ലർ ഡാഷ്‌ബോർഡിലേക്ക് പോകുക",
    howItWorks: "സപ്ലൈ മാർക്കറ്റ് എങ്ങനെ പ്രവർത്തിക്കുന്നു",
    howDesc: "നിങ്ങളുടെ ആവശ്യങ്ങളെ സുരക്ഷിതമായ നേരിട്ടുള്ള കോളുകളാക്കി മാറ്റുന്ന നാല് ലളിതമായ ഘട്ടങ്ങൾ.",
    whyChoose: "എന്തുകൊണ്ട് സപ്ലൈ മാർക്കറ്റ് തിരഞ്ഞെടുക്കണം",
    whyDesc: "ബിസിനസ്സുകൾക്കിടയിൽ വിശ്വാസം വളർത്താൻ രൂപകൽപ്പന ചെയ്ത ഒരു പ്രീമിയം, ലളിതമായ വ്യാപാര പ്ലാറ്റ്ഫോം.",
    step1Title: "ആവശ്യകത വിവരിക്കുക",
    step1Desc: "നിങ്ങളുടെ അളവ്, ഗുണനിലവാരം, സ്ഥലം എന്നിവ ടെക്സ്റ്റ് അല്ലെങ്കിൽ വോയ്സ് നിർദ്ദേശങ്ങളിലൂടെ വിവരിക്കുക.",
    step2Title: "AI മികച്ച സപ്ലയറെ കണ്ടെത്തും",
    step2Desc: "ഞങ്ങളുടെ മാച്ചിംഗ് എഞ്ചിൻ കാറ്റലോഗ് വിവരങ്ങൾ തിരയുകയും ഏറ്റവും അനുയോജ്യരായ വിതരണക്കാരെ ഗ്രേഡ് ചെയ്യുകയും ചെയ്യുന്നു.",
    step3Title: "വിതരണക്കാരന്റെ വിവരങ്ങൾ വിലയിരുത്തുക",
    step3Desc: "രൂപയിലുള്ള വിലകൾ, സ്റ്റോക്ക് അളവ്, സ്ഥലം, റേറ്റിംഗുകൾ എന്നിവ താരതമ്യം ചെയ്യുക.",
    step4Title: "നേരിട്ട് ബന്ധിപ്പിക്കുക",
    step4Desc: "സംഭാഷണം ആരംഭിക്കുന്നതിന് സുരക്ഷിതമായ ടെലിഫോൺ ഡയലർ കമ്മ്യൂണിക്കേഷൻ ഉപയോഗിക്കുക.",
    feat1Title: "വേഗത്തിലുള്ള സപ്ലയർ കണ്ടെത്തൽ",
    feat1Desc: "അനുയോജ്യരായ വിതരണക്കാരെ തൽക്ഷണം കണ്ടെത്തുക. നേരിട്ട് വിളിച്ചു സമയം കളയുന്നത് ഒഴിവാക്കൂ.",
    feat2Title: "വിശ്വസനീയമായ ബിസിനസ്സുകൾ",
    feat2Desc: "ഉയർന്ന ട്രസ്റ്റ് സ്കോറും മികച്ച പ്രകടനവുമുള്ള സാക്ഷ്യപ്പെടുത്തിയ കമ്പനികളുമായി മാത്രം ബന്ധപ്പെടുക.",
    feat3Title: "AI വോയ്സ് അസിസ്റ്റന്റ്",
    feat3Desc: "വോയ്സ് അസിസ്റ്റന്റ് മാച്ചിംഗ് വിവരങ്ങൾ കേൾക്കാൻ സഹായിക്കുന്നു.",
    feat4Title: "വിവിധ ഭാഷകൾ",
    feat4Desc: "മലയാളം, തെലുങ്ക്, ഹിന്ദി, തമിഴ്, കന്നഡ, ഇംഗ്ലീഷ്: 6 ഇന്ത്യൻ ഭാഷകളിൽ സംസാരിക്കാനും നിർദ്ദേശങ്ങൾ നേടാനും കഴിയും.",
    feat5Title: "സ്മാർട്ട് ശുപാർശകൾ",
    feat5Desc: "ഓരോ തിരഞ്ഞെടുപ്പും നിങ്ങൾക്ക് എന്തുകൊണ്ട് അനുയോജ്യമാണെന്ന് വ്യക്തമായ കാരണങ്ങളോടെ AI വിശദീകരിക്കുന്നു.",
    feat6Title: "ബിസിനസ് ബന്ധങ്ങൾ",
    feat6Desc: "കോൺടാക്റ്റുകൾ സംരക്ഷിക്കുകയും ബിസിനസ്സ് തുടരുന്നതിനായി കമ്പനി ഡയറക്ടരികൾ ഫോളോ ചെയ്യുകയും ചെയ്യുക.",

    findRightSupplier: "അനുയോജ്യനായ വിതരണക്കാരനെ കണ്ടെത്തുക",
    tellUsNeed: "നിങ്ങൾക്ക് എന്താണ് വേണ്ടതെന്ന് ഞങ്ങളോട് പറയുക. മികച്ച വിതരണക്കാരനെ കണ്ടെത്താൻ ഞങ്ങളുടെ AI സഹായിക്കും.",
    searchPlaceholder: 'ഉദാഹരണത്തിന്: "എന്റെ ഹെർബൽ ഉൽപ്പന്നങ്ങളുടെ ബിസിനസ്സിനായി എനിക്ക് 100 കിലോ പ്രീമിയം മഞ്ഞൾപ്പൊടി വേണം."',
    speakBtn: "സംസാരിക്കുക",
    findSuppliersBtn: "വിതരണക്കാരെ കണ്ടെത്തുക",
    clearBtn: "വ്യത്തിയാക്കുക",
    listeningLabel: "കേൾക്കുന്നു. നിങ്ങളുടെ ആവശ്യകത സംസാരിക്കുക...",
    matchingSuppliers: "വിതരണക്കാരെ മാച്ച് ചെയ്യുന്നു...",
    popularSearches: "ജനപ്രിയ തിരച്ചിലുകൾ:",
    processingHeuristics: "മാച്ചിംഗ് രീതികൾ പ്രോസസ്സ് ചെയ്യുന്നു",
    processingDesc: "സ്റ്റോക്ക് ഡാറ്റാബേസുകളും വിതരണ മാർഗ്ഗങ്ങളും വിശകലനം ചെയ്യുന്നു.",
    aiRecomHeading: "AI ശുപാർശ തിരഞ്ഞെടുക്കൽ",
    bestMatch: "ഏറ്റവും മികച്ച മാച്ച്",
    ratingLabel: "റേറ്റിംഗ്",
    locationLabel: "സ്ഥലം",
    availToday: "ഇന്ന് ലഭ്യമാണ്",
    matchScore: "മാച്ച് സ്കോർ",
    reasonForRecom: "ശുപാർശ ചെയ്യാനുള്ള കാരണം:",
    productOfferPrice: "ഉൽപ്പന്നത്തിന്റെ വില",
    connectBtn: "ബന്ധിപ്പിക്കുക",
    viewDetailsBtn: "വിവരങ്ങൾ കാണുക",
    saveBtn: "സംരക്ഷിക്കുക",
    savedBtn: "സംരക്ഷിച്ചു",
    aiSummaryHeading: "AI സോർസിംഗ് സംഗ്രഹം",
    reqLabel: "നിങ്ങളുടെ ആവശ്യകത",
    selSupplierLabel: "തിരഞ്ഞെടുത്ത വിതരണക്കാരൻ",
    priceLabel: "വില",
    qtyLabel: "അളവ്",
    reasonSelLabel: "തിരഞ്ഞെടുക്കാനുള്ള കാരണം",
    nextStepLabel: "അടുത്ത ഘട്ട ശുപാർശ",
    otherOptions: "മറ്റു സോഴ്സ് ചെയ്ത ഓപ്ഷനുകൾ",
    browseSuppliersManually: "വിതരണക്കാരെ നേരിട്ട് തിരയുക",
    browseDesc: "സ്ഥിരീകരിച്ച വിതരണക്കാരുടെ ഡാറ്റാബേസിലൂടെ തിരയുകയും ഫിൽട്ടർ ചെയ്യുകയും ചെയ്യുക.",
    productSearchLabel: "ഉൽപ്പന്ന തിരച്ചിൽ",
    locationCityLabel: "നഗരം / സ്ഥലം",
    productCatLabel: "ഉൽപ്പന്ന വിഭാഗം",
    allCategories: "എല്ലാ വിഭാഗങ്ങളും",
    minPriceLabel: "കുറഞ്ഞ വില (₹)",
    maxPriceLabel: "കൂടിയ വില (₹)",
    minRatingLabel: "കുറഞ്ഞ റേറ്റിംഗ്",
    allRatings: "എല്ലാ റേറ്റിംഗുകളും",
    availTodayFilter: "ഇന്ന് ലഭ്യമായവ",
    viewBtn: "കാണുക",
    followBtn: "ഫോളോ",
    followingBtn: "ഫോളോ ചെയ്യുന്നു",
    noSellersFound: "ഡയറക്ടറി തിരച്ചിലിൽ അനുയോജ്യരായ വിതരണക്കാരെ കണ്ടെത്തിയില്ല.",

    aiSpeaking: "AI സംസാരിക്കുന്നു",
    connectSupplier: "വിതരണക്കാരനെ ബന്ധിപ്പിക്കുക",
    askAi: "AIയോട് ചോദിക്കുക",
    findMore: "കൂടുതൽ കണ്ടെത്തുക",

    step1: "നിങ്ങളുടെ ആവശ്യകത മനസ്സിലാക്കുന്നു",
    step2: "വിതരണക്കാരെ തിരയുന്നു",
    step3: "വിലകൾ താരതമ്യം ചെയ്യുന്നു",
    step4: "സ്റ്റോക്ക് പരിശോധിക്കുന്നു",
    step5: "മികച്ച വിതരണക്കാരനെ തിരഞ്ഞെടുക്കുന്നു",
    step6: "മറുപടി തയ്യാറാക്കുന്നു",

    connecting: "ബന്ധിപ്പിക്കുന്നു...",
    connectingDesc: "സുരക്ഷിതമായ കോൾ ലൈനുകൾ സ്ഥാപിക്കുകയും പ്രൊഫൈലുകൾ സമന്വയിപ്പിക്കുകയും ചെയ്യുന്നു.",
    connSuccessful: "ബന്ധം വിജയകരമായി സ്ഥാപിച്ചു",
    yourIdentity: "നിങ്ങളുടെ ഐഡന്റിറ്റി",
    supplierSourced: "സോഴ്സ് ചെയ്ത സപ്ലയർ",
    connConnected: "ബന്ധിപ്പിച്ചു",
    connSuccessText: "വാങ്ങുന്നയാളും വിതരണക്കാരനും ഇപ്പോൾ ബന്ധപ്പെട്ടിരിക്കുന്നു. നിങ്ങൾക്ക് നേരിട്ട് ചർച്ച തുടരാം.",
    callSalesBtn: "സെയിൽസ് പ്രതിനിധിയെ വിളിക്കുക",
    doneBtn: "കഴിഞ്ഞു",

    activeListings: "സജീവ കാറ്റലോഗ് ലിസ്റ്റിംഗുകൾ",
    activeOrders: "സജീവ ഓർഡറുകൾ",
    connectedBuyers: "ബന്ധിപ്പിച്ച വാങ്ങുന്നവർ",
    revenueLabel: "വരുമാനം",
    salesValue: "രേഖപ്പെടുത്തിയ വിൽപന മൂല്യം",
    aiSourcingSug: "AI സോർസിംഗ് ശുപാർശകൾ",
    inventorySourcingCat: "ഇൻവെന്ററി സോർസിംഗ് കാറ്റലോഗ്",
    inventorySourcingDesc: "ഉപഭോക്തൃ ആവശ്യങ്ങൾക്ക് അനുയോജ്യമായ നിങ്ങളുടെ ഉൽപ്പന്നങ്ങളുടെ വിവരങ്ങൾ നിയന്ത്രിക്കുക.",
    addProduct: "ഉൽപ്പന്നം ചേർക്കുക",
    editProduct: "ഉൽപ്പന്നം എഡിറ്റ് ചെയ്യുക",
    deleteProduct: "ഉൽപ്പന്നം ഇല്ലാതാക്കുക",
    recentConnectedBuyers: "അടുത്തിടെ ബന്ധിപ്പിച്ച വാങ്ങുന്നവർ",
    recentConnectedDesc: "സുരക്ഷിത AI വോയ്സ് കോളുകൾ വഴി സ്ഥാപിച്ച ബന്ധങ്ങൾ.",
    viewBuyer: "ബയർ വിവരങ്ങൾ",
    contactBuyer: "ബയറുമായി ബന്ധപ്പെടുക",
    saveChanges: "മാറ്റങ്ങൾ സംരക്ഷിക്കുക",
    cancel: "റദ്ദാക്കുക",
    availableTodayModal: "ഇന്ന് ലഭ്യമാണ് (ഉടനടി അയക്കൽ സജീവമാണ്)",
    modalAvailable: "ലഭ്യമാണ്",

    prodNameField: "ഉൽപ്പന്നത്തിന്റെ പേര്",
    catField: "വിഭാഗം",
    priceField: "വില",
    qtyField: "അളവ്",
    qualityField: "ഗുണനിലവാരം",
    locField: "നഗരം",
    busNameField: "ബിസിനസ്സ് നാമം",
    phoneField: "ഫോൺ നമ്പർ",
    availabilityField: "ലഭ്യത",
    actionsField: "നടപടികൾ",

    userConsole: "യൂസർ കൺസോൾ",
    userConsoleDesc: "നിങ്ങളുടെ ബിസിനസ്സ് ബന്ധങ്ങളും പ്രവർത്തന ചരിത്രവും ഭാഷാ മുൻഗണനകളും നിയന്ത്രിക്കുക.",
    profileIdentity: "പ്രൊഫൈൽ ഐഡന്റിറ്റി",
    hotlineConnections: "ബന്ധങ്ങളുടെ ഹോട്ട്‌ലൈൻ",
    recentActivity: "സമീപകാല പ്രവർത്തനം",
    consoleSettings: "കൺസോൾ ക്രമീകരണങ്ങൾ",
    headquarters: "ആസ്ഥാനം",
    activeCatalogReg: "സജീവ കാറ്റലോഗ് രജിസ്ട്രി",
    bothBadge: "രണ്ടും (വാങ്ങുന്നയാളും വിതരണക്കാരനും)",
    procurementManager: "സംഭരണ & മൊത്തവ്യാപാര വിഭാഗം മാനേജർ",
    corporateEmail: "കോർപ്പറേറ്റ് ഇമെയിൽ",
    mobilePhone: "മൊബൈൽ ഫോൺ",
    connHotlineTitle: "ബിസിനസ്സ് ബന്ധങ്ങളുടെ ഹോട്ട്‌ലൈൻ",
    connHotlineDesc: "വിശ്വസനീയമായ വിതരണക്കാരുമായി നേരിട്ട് ബന്ധപ്പെടുക. സംരക്ഷിച്ച കോൺടാക്റ്റുകൾക്കായി AI ആവശ്യവുമില്ല.",
    removeConn: "ഒഴിവാക്കുക",
    sendMessage: "സന്ദേശം അയക്കുക",
    buyerActivity: "വാങ്ങുന്നയാളുടെ പ്രവർത്തനം",
    sellerActivity: "വിതരണക്കാരന്റെ പ്രവർത്തനം",
    recentSearches: "സമീപകാല തിരച്ചിലുകൾ",
    recentConversationalLogs: "സമീപകാല വോയ്സ് സംഭാഷണങ്ങൾ",
    savedSourcedSuppliers: "സംരക്ഷിച്ച വിതരണക്കാർ",
    hotlinePurchaseHistory: "ഹോട്ട്‌ലൈൻ വാങ്ങൽ ചരിത്രം",
    connectedBuyerActions: "ബന്ധിപ്പിച്ച ബയർ നടപടികൾ",
    supplierCatalogChanges: "കാറ്റലോഗ് മാറ്റങ്ങൾ",
    catalogOrders: "കാറ്റലോഗ് ഓർഡറുകൾ",
    hotRestockSug: "ആവശ്യമായ സ്റ്റോക്ക് ശുപാർശ",
    systemPref: "സിസ്റ്റം മുൻഗണനകൾ",
    systemPrefDesc: "വോയ്സ് മുൻഗണനകൾ, ഇൻപുട്ട് ക്രമീകരണങ്ങൾ, തീം മോഡുകൾ, അറിയിപ്പുകൾ എന്നിവ നിയന്ത്രിക്കുക.",
    speechLanguageInterface: "സംഭാഷണ ഭാഷാ ഇന്റർഫേസ്",
    themeMode: "തീം മോഡ്",
    toggleModeTheme: "തീം മാറ്റുക",
    voiceOutputEngine: "വോയ്സ് ഔട്ട്പുട്ട് എഞ്ചിൻ",
    speechMicInput: "മൈക്രോഫോൺ ഇൻപുട്ട്",
    notificationsCenter: "അറിയിപ്പ് കേന്ദ്രം",
    notifConnAlerts: "കണക്ഷൻ മാറ്റങ്ങളുടെ അലേർട്ടുകൾ",
    notifStockAlerts: "സ്റ്റോക്ക് അപ്‌ഡേറ്റുകളുടെ അലേർട്ടുകൾ",

    salesAiAssistant: "സെയിൽസ് AI അസിസ്റ്റന്റ്",
    aiBusinessAdvisor: "AI ബിസിനസ് ഉപദേശകൻ",
    askSourcingAdvisor: "ആலோசകനോട് ചോദിക്കുക:",
    typeCustomQuestion: "ചോദ്യം ടൈപ്പ് ചെയ്യുക...",
    analyzingSales: "വിൽപന വിശകലനം ചെയ്യുന്നു...",
    salesAiWelcome: "നമസ്കാരം! ഞാൻ നിങ്ങളുടെ സെയിൽസ് AI അസിസ്റ്റന്റാണ്. എനിക്ക് നിങ്ങളുടെ കാറ്റലോഗ് വിശകലനം ചെയ്യാനും ആവശ്യങ്ങൾ മുൻകൂട്ടി കാണാനും ബിസിനസ്സ് റിപ്പോർട്ടുകൾ തയ്യാറാക്കാനും കഴിയും. ആരംഭിക്കാൻ താഴെയുള്ള ചോദ്യങ്ങളിൽ ഒന്ന് തിരഞ്ഞെടുക്കുക:",

    chipSoldToday: "ഇന്ന് എത്ര ഉൽപ്പന്നങ്ങൾ വിറ്റുപോയി?",
    chipSellsMost: "ഏത് ഉൽപ്പന്നമാണ് ഏറ്റവും കൂടുതൽ വിൽക്കപ്പെടുന്നത്?",
    chipRestock: "ഞാൻ ഏത് ഉൽപ്പന്നമാണ് വീണ്ടും ശേഖരിക്കേണ്ടത്?",
    chipDecreasing: "എന്തുകൊണ്ടാണ് വിൽപന കുറയുന്നത്?",
    chipPricing: "മെച്ചപ്പെട്ട വില നിർദ്ദേശിക്കുക.",
    chipTrends: "ഉപഭോക്തൃ വാങ്ങൽ രീതികൾ കാണിക്കുക.",
    chipInventory: "സ്റ്റോക്ക് മെച്ചപ്പെടുത്തലുകൾ ശുപാർശ ചെയ്യുക.",
    chipWeekly: "വാരപ്പതിപ്പ് റിപ്പോർട്ട് തയ്യാറാക്കുക.",
    chipMonthly: "മാസപ്പതിപ്പ് റിപ്പോർട്ട് തയ്യാറാക്കുക.",
    chipDemand: "ആവശ്യം പ്രവചിക്കുക.",
    chipBestSelling: "ഏറ്റവും കൂടുതൽ വിൽക്കുന്ന ഉൽപ്പന്നങ്ങൾ നിർദ്ദേശിക്കുക.",

    replySoldToday: "ഇന്നത്തെ ലോഗുകൾ പ്രകാരം, വർമ്മ ഫുഡ് ഇൻഡസ്ട്രീസ് ₹18,000 വിലമതിക്കുന്ന 150 കിലോ പ്രീമിയം മഞ്ഞൾപ്പൊടി വാങ്ങി. നിങ്ങളുടെ ഓർഡർ വിജയകരമായി പൂർത്തിയായി.",
    replySellsMost: "നിങ്ങളുടെ കാറ്റലോഗിൽ മികച്ച പ്രകടനം മഞ്ഞൾപ്പൊടിക്കാണ്. ഈ മാസത്തിൽ 720 അന്വേഷണങ്ങൾ ഇതിനായി വന്നു.",
    replyRestock: "വിപണി ആവശ്യകത പരിശോധിച്ചതിൽ മഞ്ഞൾപ്പൊടിക്ക് വലിയ ആവശ്യക്കാരുണ്ട്. ഈ ആഴ്ച തിരച്ചിലുകൾ 22% വർദ്ധിച്ചു. ആവശ്യത്തിന് സ്റ്റോക്ക് സൂക്ഷിക്കാൻ 2,000 കിലോ കൂടി ചേർക്കാൻ ശുപാർശ ചെയ്യുന്നു.",
    replyDecreasing: "പ്രാദേശിക ബസുമതി അരി വിൽപന വർദ്ധിച്ചെങ്കിലും, മഴ കാരണം വാറങ്കൽ, ചെന്നൈ മേഖലകളിൽ സിമന്റ്, ഇരുമ്പ് കമ്പികളുടെ ആവശ്യകതയിൽ 4% കുറവുണ്ടായി. മഞ്ഞളും അരിയും മികച്ച നിലയിലാണ്.",
    replyPricing: "പ്രാദേശിക ആവശ്യം വർദ്ധിച്ചതിനാൽ, മഞ്ഞൾപ്പൊടിയുടെ വില കിലോയ്ക്ക് ₹120-ൽ നിന്ന് ₹125 ആയി ഉയർത്താൻ ഞങ്ങൾ നിർദ്ദേശിക്കുന്നു. ഇത് നിങ്ങളുടെ പ്രതിവാര ലാഭം ₹1,500 വർദ്ധിപ്പിക്കും.",
    replyTrends: "മൊത്തക്കച്ചവടക്കാർ വലിയ ഓർഡറുകൾ നൽകുന്നതിന് മുമ്പ് ഗുണനിലവാരം പരിശോധിക്കാൻ ആദ്യം ചെറിയ സാമ്പിളുകൾ (50 മുതൽ 200 കിലോ വരെ) വാങ്ങാൻ താൽപ്പര്യപ്പെടുന്നു.",
    replyInventory: "സ്റ്റോക്ക് ശുപാർശകൾ:\n1. ക്വാളിറ്റി സർട്ടിഫിക്കറ്റ് ലഭിക്കുന്നതിന് തേക്ക് തടിയുടെ ഗുണനിലവാരം മെച്ചപ്പെടുത്തുക.\n2. ഡെലിവറി വൈകുന്നത് ഒഴിവാക്കാൻ പാക്കേജിംഗ് പെട്ടികൾ എപ്പോഴും 5,000-ൽ കൂടുതൽ സൂക്ഷിക്കുക.",
    replyWeekly: "പ്രതിവാര പ്രകടന റിപ്പോർട്ട് (05 ജൂലൈ 2026):\n• സജീവ ലിസ്റ്റിംഗുകൾ: 2\n• ബന്ധിപ്പിച്ച ബയർമാർ: 128\n• ആകെ വരുമാനം: ₹1.85 ലക്ഷം\n• ഓർഡർ വളർച്ചാ നിരക്ക്: +12%\n• വിശ്വസ്തത റേറ്റിംഗ്: 4.8★",
    replyMonthly: "പ്രതിമാസ സോർസിംഗ് റിപ്പോർട്ട്:\n• തിരച്ചിലുകളുടെ എണ്ണം: 1,420\n• വിജയകരമായ കണക്ഷനുകൾ: 128\n• മികച്ച വിഭാഗങ്ങൾ: മഞ്ഞൾ, സോന മസൂരി അരി\n• പ്രതിമാസ വളർച്ചാ നിരക്ക്: +14.5% MoM",
    replyDemand: "ആവശ്യകത പ്രവചനം (അടുത്ത 30 ദിവസങ്ങൾ):\n• മഞ്ഞൾ സോർസിംഗ്: വളരെ കൂടുതൽ (+18% പ്രവചിക്കുന്നു)\n• അരി സോർസിംഗ്: സ്ഥിരതയുള്ളത് (+6% പ്രവചിക്കുന്നു)\n• സിമന്റ്/ഇരുമ്പ്: മിതമായ വളർച്ച (+4% ഹൈദരാബാദിൽ)",
    replyBestSelling: "ദക്ഷിണേന്ത്യയിൽ ഏറ്റവും കൂടുതൽ വിറ്റഴിക്കപ്പെടുന്ന ഉൽപ്പന്നങ്ങളിൽ ഈറോഡ് ഓർഗാനിക് മഞ്ഞൾപ്പൊടി, നെല്ലൂർ സോന മസൂരി അരി, ഭൂകമ്പ പ്രതിരോധശേഷിയുള്ള TMT ഇരുമ്പ് കമ്പികൾ എന്നിവ ഉൾപ്പെടുന്നു.",
    replyGeneric: "നമസ്കാരം! ഞാൻ നിങ്ങളുടെ ചോദ്യം വിശകലനം ചെയ്തു. നിങ്ങളുടെ കാറ്റലോഗ് ഉൽപ്പന്നങ്ങളുടെ അടിസ്ഥാനത്തിൽ, പുതിയ ഓർഡറുകൾ സ്വീകരിക്കാൻ സ്റ്റോക്ക് എപ്പോഴും തയ്യാറാക്കി നിർത്തുന്നത് പ്രധാനമാണ്. കൂടുതൽ വിവരങ്ങൾക്ക് ചോദിക്കുക!"
  }
};
